#! /usr/bin/env python"),
# -*- coding: utf-8 -*-"),

import random
import codecs


DCC500_VERBI = [
("ἀγγέλλω, ἀγγελῶ, ἤγγειλα, ἤγγελκα, ἤγγελμαι, ἠγγέλθην", "annunciare"),
("ἄγω, ἄξω, ἤγαγον, ἦχα, ἦγμαι, ἤχθην", "condurre, portare"),
("ἀδικέω, ἀδικήσω, ἠδίκησα, ἠδίκηκα, ἠδίκημαι, ἠδικήθην", "operare ingiustamente; maltrattare"),
("αἱρέω, αἱρήσω, (aor II) εἷλον, ᾕρηκα, ᾕρημαι, ᾑρέθην", "prendere; espugnare; (al medio) scegliere"),
("αἴρω, ἀρῶ, ἦρα, ἦρκα, ἦρμαι, ἤρθην", "sollevare"),
("αἰσθάνομαι, αἰσθήσομαι, (aor II) ᾐσθόμην, ᾔσθημαι", "percepire, sentire; comprendere"),
("αἰτέω, αἰτήσω, ᾔτησα, ᾔτηκα, ᾔτημαι, ᾐτήθην", "domandare; desiderare"),
("ἀκούω, ἀκούσομαι, ἤκουσα, ἀκήκοα, (piuccheperfetto) ἠκηκόη/ἀκηκόη, ἠκούσθην", "sentire; ascoltare"),
("ἁλίσκομαι, ἁλώσομαι, (aor II) ἑάλων, ἑάλωκα", "essere preso, conquistato (all'attivo si usa αἱρέω)"),
("ἁμαρτάνω, ἁμαρτήσομαι, ἡμάρτησα, (aor II) ἥμαρτον, ἡμάρτηκα, ἡμάρτημαι, ἡμαρτήθην", "non cogliere, fallire (+gen); sbagliare, rendersi colpevole, peccare"),
("ἀναιρέω, ἀναιρήσω, ἀνεῖλον, ἀνῄρηκα, ἀνῄρημαι, ἀνῃρέθην", "distruggere; sollevare; dare un responso"),
("ἀξιόω, ἀξιώσω, ἠξίωσα, ἠξίωκα, ἠξίωμαι, ἠξιώθην", "ritenere giusto, ritenere degno"),
("ἀπαλλάσσω, ἀπαλλάξω, ἀπήλλαξα, ἀπήλλαχα, ἀπήλλαγμαι, ἀπηλλάχθην/ἀπηλλάγην", "cambiare; (al medio) liberarsi di"),
("ἀποδίδωμι, ἀποδώσω, ἀπέδωκα, ἀποδέδωκα, ἀποδέδομαι, ἀπεδόθην", "restituire; permettere; (al medio) vendere"),
("ἀποθνῄσκω, ἀποθανοῦμαι, (aor II) ἀπέθανον, ἀποτέθνηκα", "morire"),
("ἀποκρίνω, ἀποκρινῶ, ἀπεκρινάμην, ἀπεκρίθη", "separare, scegliere; (al medio) rispondere"),
("ἀποκτείνω, ἀποκτενῶ, ἀπέκτεινα, ἀπέκτονα", "uccidere"),
("ἀπόλλυμι, ἀπολῶ, ἀπώλεσα, (aor II) medio ἀπωλόμην, (perfetto) ἀπολώλεκα (“ho distrutto completamente”) o ἀπόλωλα (“sono annullato”)", "distruggere; (al medio) morire"),
("ἄρχω, ἄρξω, ἦρξα, ἦργμαι, ἤρχθην", "comincio (+gen); conduco, governo (+gen)"),
("ἀφίημι, ἀφήσω, ἀφῆκα, ἀφεῖκα, ἀφεῖμαι, ἀφείθην", "lasciar andare"),
("ἀφαιρέω, ἀφαιρήσω, ἀφεῖλον, ἀφῄρηκα, ἀφῄρημαι, ἀφῃρέθην", "togliere, portare via; separare"),
("ἀφικνέομαι, ἀφίξομαι, (aor II) ἀφικόμην, ἀφῖγμαι", "arrivare, giungere"),
("βαίνω, βήσομαι, (aor II) ἔβην, βέβηκα", "camminare, andare, tornare"),
("βάλλω, βαλῶ, (aor II) ἔβαλον, βέβληκα, βέβλημαι, ἐβλήθην", "lanciare, scagliare, colpire (+acc) con (+dat)"),
("βλέπω, βλέψομαι, ἔβλεψα", "vedere; guardare"),
("βοηθέω, βοηθήσω, ἐβοήθησα, βεβοήθηκα", "aiutare, soccorrere (+dat)"),
("βουλεύω βουλεύσω, ἐβούλευσα, βεβούλευκα, βεβούλευμαι, ἐβουλεύθην", "progettare, decidere; (al medio) consigliarsi, decidere"),
("βούλομαι, βουλήσομαι, βεβούλημαι, ἐβουλήθην", "(+infinito) volere; ὁ βουλόμενος colui al quale piace"),
("γίγνομαι, γενήσομαι, (aor II) ἐγενόμην, γέγονα, γεγένημαι, ἐγενήθην", "diventare; verificarsi; essere"),
("γιγνώσκω, γνώσομαι, ἔγνων, ἔγνωκα, ἔγνωσμαι, ἐγνώσθην", "conoscere; pensare; decidere"),
("γράφω, γράψω, ἔγραψα, γέγραφα, γέγραμμαι, ἐγράφην", "scrivere"),
("δέδοικα [perfetto con forza di presente], δείσομαι, ἔδεισα", "temere"),
("δεῖ, δεήσει, (imperfetto) ἔδει", "si deve, è necessario (+acc e infinito)"),
("δείκνυμι, δείξω, ἔδειξα, δέδειχα, δέδειγμαι, ἐδείχθην", "mostrare, spiegare"),
("δέχομαι, δέξομαι, ἐδεξάμην, δέδεγμαι, ἐδεδέχθην", "ricevere, prendere; accogliere, preferire"),
("δέω, δεήσω, ἐδέησα, δεδέηκα, δεδέημαι, ἐδεήθην", "mancare (+gen)"),
("δηλόω, δηλώσω, ἐδήλωσα, δεδήλωκα, ἐδηλώθην", "mostrare, dichiarare, spiegare"),
("διαφέρω, διοίσω, 1 aor. διήνεγκα, (aor II) διήνεγκον, διενήνοχα, διενήνεγμαι", "trasportare; spargere; differire; (impers.) διαφέρει fa differenza a (+dat)"),
("διαφθείρω, διαφθερῶ, διέφθειρα, διέφθαρκα, διέφθαρμαι, διεφθάρην", "distruggere; mandare in rovina"),
("διδάσκω, διδάξω, ἐδίδαξα, δεδίδαχα, δεδίδαγμαι, ἐδιδάχθην", "insegnare"),
("δίδωμι, δώσω, ἔδωκα, δέδωκα, δέδομαι, ἐδόθην", "dare"),
("διώκω, διώξομαι, ἐδίωξα, δεδίωχα, ἐδιώχθην", "inseguire; perseguire penalmente"),
("δοκέω, δόξω, ἔδοξα", "pensare (+acc e infinito); sembrare; (impersonale) δοκεῖ μοι mi sembra"),
("δράω, δράσω, ἔδρασα, δέδρακα, δέδραμαι, ἐδράσθην", "fare"),
("δύναμαι, δυνήσομαι, ἐδυνήθην, δεδύνημαι", "(+infinito) potere"),
("ἐάω, ἐάσω, εἴασα", "permettere (+acc e infinito); lasciare, lasciar solo"),
("ἐθέλω, ἐθελήσω, ἠθέλησα, ἠθέληκα", "(+infinito) volere; desiderare"),
("εἶδον, (aor II) di ὁράω, (infinito att) ἰδεῖν, (infinito medio) ἰδέσθαι", "io vidi"),
("εἰμί, ἔσομαι, (imperfetto) ἦν, (infinito) εἶναι", "essere, esistere"),
("εἶμι, infinito ἰέναι, participio ἰών, ἰοῦσα, ἰόν", "andrò (fut. di ἔρχομαι)"),
("εἶπον", "io dissi, io parlai, (aor II) → λέγω, φημί"),
("ἐλαύνω, ἐλῶ, ἤλασα, ελήλακα, ἐλήλαμαι, ἠλάθην", "mettere in moto; avanzare"),
("ἔοικα, participio εἰκώς", "essere simile, sembrare (+dat); convenire"),
("ἕπομαι, ἕψομαι, (aor II) ἑσπόμην", "seguire"),
("ἐργάζομαι, ἐργάσομαι, εἰργασάμην, εἴργασμαι", "lavorare, operare"),
("ἔρομαι, ἐρήσομαι, (aor II) ἠρόμην", "ask, ask one about (+double acc)"),
("ἔρχομαι, fut. εἶμι/ἐλεύσομαι, (aor II) ἦλθον, ἐλήλυθα", "venire"),
("ἐρωτάω, ἐρήσομαι, (aor II) ἠρόμην", "domandare qualcosa (acc) a qualcuno (acc); chiedere"),
("εὑρίσκω, εὑρήσω, (aor II) ηὗρον/εὗρον, ηὕρηκα/εὕρηκα, εὕρημαι, εὑρέθην", "trovare"),
("ἔχω, ἕξω/σχήσω, (aor II) ἔσχον, ἔσχηκα, (imperfetto) εἶχον", "avere; stare (+avv)"),
("ἡγέομαι, ἡγήσομαι, ἡγησάμην, ἥγημαι", "guidare; ritenere"),
("ἥκω, ἥξω, pf. ἧκα", "essere giunto"),
("ζάω, ζήσω, ἔζησα, ἔζηκα", "vivere"),
("ζητέω, ζητήσω, ἐζήτησα, ἐζήτηκα", "cercare"),
("θαυμάζω, θαυμάσομαι, ἐθαύμασα, τεθαύμακα, τεθαύμασμαι, ἐθαυμάσθην", "meravigliarsi"),
("θνῄσκω, (aor II) ἔθανον, τέθνηκα, θανοῦμαι", "morire, essere uccisi"),
("θύω, θύσω, ἔθυσα, τέθυκα, τέθυμαι, ἐτύθην", "sacrificare"),
("ἵημι, ἥσω, ἧκα, εἷκα, εἷμαι, εἵθην", "mandare; spedire; mettere in moto; (al medio) affrettarsi, correre verso"),
("ἵστημι, στήσω, ἔστησα, (aor II) ἔστην, ἕστηκα, (piuccheperfetto) εἱστήκη, ἐστάθην", "collocare; (al medio) stare"),
("καθίστημι, καταστήσω, κατέστησα, κατέστην, καθέστηκα, (piuccheperfetto) καθειστήκη, κατεστάθην", "disporre, stabilire; portare in un certo stato, rendere"),
("καλέω, καλῶ, ἐκάλεσα, κέκληκα, κέκλημαι, ἐκλήθην", "chiamare, convocare"),
("καταλαμβάνω, καταλήψομαι, κατέλαβον, κατείληφα, κατείλημμαι, κατελήφθην", "afferrare, prendere, arrestare, costringere"),
("κατασκευάζω, κατασκευάσω, κατεσκεύασα", "preparare, equipaggiare, fornire"),
("κατηγορέω, κατηγορήσω, κατηγόρησα, κατηγόρηκα, κατηγόρημαι, κατηγορήθην", "accusare, incolpare (+gen)"),
("κελεύω, κελεύσω, ἐκέλευσα, κεκέλευκα, κεκέλευσμαι, ἐκελεύσθην", "ordinare, invitare (+acc e infinito)"),
("κεῖμαι, κείσομαι", "giacere, trovarsi, essere stabilito (usato come perfetto passivo di τίθημι)"),
("κινέω, κινήσω, ἐκίνησα, κεκίνηκα, κεκίνημαι, ἐκινήθην", "muovere, mettere in moto; agitare"),
("κομίζω, κομιῶ, ἐκόμισα, κεκόμικα, κεκόμισμαι, ἐκομίσθην", "prendersi cura di, provvedere a"),
("κρατέω, κρατήσω, ἐκράτησα, κεκράτηκα, κεκράτημαι, ἐκρατήθην", "vincere, conquistare, prevalere, eccellere (+gen)"),
("κρίνω, κρινῶ, ἔκρινα, κέκρικα, κέκριμαι, ἐκρίθην", "giudicare, decidere, determinare"),
("κτάομαι, κτήσομαι, ἐκτησάμην, κέκτημαι", "acquistare, guadagnare; possedere"),
("κωλύω, κωλύσω, ἐκώλυσα, κεκώλυκα, κεκώλυμαι, ἐκωλύθην", "impedire (+acc e infinito)"),
("λαλέω, λαλήσω, ἐλάλησα, λελάληκα, ἐλαλήθην", "parlare, chiacchierare, raccontare"),
("λαμβάνω, λήψομαι, ἔλαβον, εἴληφα, εἴλημμαι, ἐλήφθην", "prendere"),
("λανθάνω, λήσω, ἔλαθον, λέληθα", "nascondersi; sfuggire all'attenzione di (+acc e nominativo del participio), essere ignoto; (al medio e passivo) dimenticare, dimenticarsi"),
("λέγω, ἐρῶ, εἶπον, εἴρηκα, λέλεγμαι, ἐλέχθην/ἐρρήθην", "dire; parlare"),
("λείπω, λείψω, ἔλιπον, λέλοιπα, λέλειμμαι, ἐλείφθην", "lasciare, abbandonare"),
("λύω, λύσω, ἔλυσα, λέλυκα, λέλυμαι, ἐλύθην", "sciogliere, liberare; distruggere"),
("μανθάνω, μαθήσομαι, ἔμαθον, μεμάθηκα", "imparare"),
("μάχομαι, μαχοῦμαι, ἐμαχεσάμην, μεμάχημαι", "combattere contro (+dat)"),
("μέλλω, μελλήσω, ἐμέλλησα", "(+infinito) essere in procinto di, pensare di fare"),
("μένω, μενῶ, ἔμεινα, μεμένηκα", "stare, rimanere; resistere; aspettare"),
("μίγνυμι, μείξω, ἔμειξα, μέμειγμαι, ἐμείχθην", "mescolare"),
("μιμνήσκω, μνήσω, έμνησα, (perfetto) μέμνημαι, ἐμνήσθην", "rammentare; (al perfetto medio) ricordarsi"),
("νικάω, νικήσω, ἐνίκησα, νενίκηκα, νενίκημαι, ἐνικήθην", "vincere, conquistare"),
("νομίζω, νομιῶ, ἐνόμισα, νενόμικα, νενόμισμαι, ἐνομίσθην", "pensare, ritenere (+acc e infinito); essere abituati a (+infinito)"),
("οἶδα, infinito εἰδέναι, (imperfetto) ἴσθι, [piuccheperfetto usato come imperfetto] ᾔδειν", "sapere [perfetto con forza di presente]; sapere come (+infinito)"),
("οἰκέω, οἰκήσω, ᾤκησα, ᾤκηκα, ᾠκήθην", "abitare, insediarsi"),
("οἴομαι/οἶμαι, οἰήσομαι, (imperfetto) ᾤμην, aor. ᾠήθην", "pensare (+acc e infinito)"),
("ὁμολογέω, ὁμολογήσω, ὡμολόγησα, ὡμολόγηκα, ὡμολόγημαι, ὡμολογήθην", "accordarsi, essere d'accordo (+dat)"),
("ὀνομάζω, ὀνομάσω, ὠνόμασα, ὠνόμακα, ὠνόμασμαι, ὠνομάσθην", "chiamare per nome"),
("ὁράω, ὄψομαι, (aor II) εἶδον, ἑόρακα/ἑώρακα, ὤφθην, (imperfetto) ἑώρων", "vedere; guardare"),
("ὁρμάω, ὁρμήσω, ὥρμησα, ὥρμηκα, ὥρμημαι, ὡρμήθην", "mettere in moto, spingere; (intrans.) partire, affrettarsi"),
("πάρειμι", "essere presenti; (impersonale) πάρεστί μοι dipende da me; τὰ παρόντα le circostanze presenti; τὸ παρόν solo ora"),
("παρέχω, παρέξω, παρέσχον, παρέσχηκα, (imperfetto) παρεῖχον", "procurare"),
("παραδίδωμι, παραδώσω, παρέδωκα, παραδέδωκα, παραδέδομαι, παρεδόθην", "trasmttere, consegnare; cedere"),
("παρασκευάζω, παρασκευάσω, παρεσκεύασα", "approntare, preparare"),
("πάσχω, πείσομαι, ἔπαθον, πέπονθα", "soffrire, provare; essere affetti in un certo modo (+avv)"),
("παύω, παύσω, ἔπαυσα, πέπαυκα, πέπαυμαι, ἐπαύθην", "far cessare; (la medio) smettere"),
("πείθω, πείσω, ἔπεισα, πέποιθα, πέπεισμαι, ἐπείσθην", "persuadere; (al medio e passivo) obbedire, credere in (+dat)"),
("πειράω (di solito al medio πειράομαι), πειράσομαι, ἐπείρασα, πεπείραμαι, ἐπειράθην", "provare, tentare; fare prova di (+gen)"),
("πέμπω, πέμψω, ἔπεμψα, πέπομφα, πέπεμμαι, ἐπέμφθην", "mandare, inviare"),
("πίνω, πίομαι, (aor II) ἔπιον, πέπωκα, πέπομαι, επόθην", "bere"),
("πίπτω, πεσοῦμαι, ἔπεσον, πέπτωκα", "cadere; soccombere"),
("πιστεύω, πιστεύσω, ἐπίστευσα, πεπίστευκα, πεπίστευμαι, ἐπιστεύθην", "fidarsi, credere, trust, affidarsi, credere in (+dat)"),
("πλέω, πλεύσομαι, ἔπλευσα, πέπλευκα, πέπλευσμαι, ἐπλεύσθην", "navigare"),
("ποιέω, ποιήσω, ἐποίησα, πεποίηκα, πεποίημαι, ἐποιήθην", "fare; creare; (al medio) considerare, riconoscere"),
("πολεμέω, πολεμήσω, ἐπολέμησα, πεπολέμηκα", "fare guerra; litigare"),
("πορεύω, πορεύσω, ἐπόρευσα, πεπόρευμαι, ἐπορεύθην", "portare; (al medio e passivo) recarsi, andare, viaggiare"),
("πράσσω, πράξω, ἔπραξα, πέπραχα, πέπραγμαι, ἐπράχθην", "fare, eseguire; fare in un certo modo (+avv)"),
("προσήκω προσήξω", "convenire; essere adatto (+dat); arrivare a; οἱ προσήκοντες i parenti; τὰ προσήκoντα i doveri"),
("προστίθημι, προσθήσω, προσέθηκα, προστέθηκα, προστέθειμαι (ma comunemente προσκεῖμαι), προσετέθην", "applicare; adoperare; (al medio) unirsi a"),
("πυνθάνομαι, πεύσομαι, (aor II) ἐπυθόμην, πέπυσμαι", "informarsi; venire a sapere; chiedere a proposito di (+gen)"),
("σκοπέω, σκοπήσω, ἐσκόπησα", "osservare, guardare; considerare; esaminare"),
("συμβαίνω, συμβήσομαι, (aor II) συνέβην, συμβέβηκα", "incontrare; accordarsi, correspond; accadere, succedere; avvenire in un certo modo (+avv), riuscire"),
("συμφέρω, συνοίσω, συνήνεγκα", "beneficiare, essere utile o vantaggioso a (+dat); (impers.) συμφέρει conviene, è vantaggioso (+infinito); τὸ συμφέρον l'utile, il vantaggio, il profitto"),
("σῴζω, σώσω, ἔσωσα, σέσωκα, ἐσώθην", "salvare"),
("τάσσω, τάξω, ἔταξα, τέταχα, τέταγμαι, ἐτάχθην", "disporre; schierare"),
("τελευτάω, τελευτήσω, ἐτελεύτησα, τετελεύτηκα, τετελεύτημαι, ἐτελευτήθην", "finire; morire"),
("τέμνω, τεμῶ, (aor II) ἔτεμον, τέτμηκα, τέτμημαι, ἐτμήθην", "tagliare, dividere, spaccare"),
("τίθημι, θήσω, ἔθηκα, τέθηκα, τέθειμαι (ma di solito κεῖμαι), ἐτέθην", "porre, collocare; stabilire, ordinare, istituire; mettere in un certo stato"),
("τίκτω, τέξω/τέξομαι, ἔτεκον, τέτοκα, τέτεγμαι, ἐτέχθην", "generare, dare alla luce, produrre"),
("τιμάω, τιμήσω, ἐτίμησα, τετίμηκα, τετίμημαι, ἐτιμήθην", "onorare"),
("τολμάω, τολμήσω, ἐτόλμησα, τετόλμηκα, τετόλμημαι, ἐτολμήθην", "osare, avere coraggio; sopportare"),
("τρέπω, τρέψω, ἔτρεψα, τέτροφα, ἐτράπην", "volgere"),
("τρέφω, θρέψω, ἔθρεψα, τέθραμμαι, ἐτράφην", "nutrire"),
("τυγχάνω, τεύξομαι, ἔτυχον, τετύχηκα. τέτυγμαι, ἐτύχθην", "avere dalla sorte (+gen); ottenere, trovarsi (+participio)"),
("ὑπάρχω, ὑπάρξω, ὑπῆρξα, ὑπῆργμαι, ὑπήρχθην", "esserci, esistere; τὰ ὑπάρχοντα le circostanze attuali"),
("ὑπολαμβάνω, ὑπολήψομαι, ὑπέλαβον, ὑπείληφα, ὑπείλημμαι, ὑπελήφθην", "prendere; rispondere; pensare"),
("φαίνω, φανῶ, ἔφηνα, πέφηνα, πέφασμαι, ἐφάνην", "mostrare; (al medio) apparire (+participio/infinito)"),
("φέρω, οἴσω, (aor I) ἤνεγκα, (aor II) ἤνεγκον, ἐνήνοχα, ἐνήνεγμαι, ἠνέχθην", "portare; produrre; φέρε come now, well"),
("φεύγω, φεύξομαι, ἔφυγον, πέφευγα", "fuggire; essere imputato"),
("φημί, φήσω, (imperfetto) ἔφην", "affermare; οὐ φημί negare, dire che...no"),
("φοβέω, φοβήσω, ἐφόβησα, πεφόβημαι, ἐφοβήθην", "far paura; (al medio e passivo) temere, fuggire"),
("φράζω, φράσω, ἔφρασα, πέφρακα, πέφρασμαι, ἐφράσθην", "rivelare, annunciare; (al medio e passivo) riflettere"),
("φρονέω, φρονήσω, ἐφρόνησα", "pensare (+infinito); essere propenso a (+avv e dat.)"),
("φυλάσσω, φυλάξω, ἐφύλαξα, πεφύλαχα, πεφύλαγμαι, ἐφυλάχθην", "fare la guardia, difendere; (al medio) guardarsi da (+acc)"),
("φύω, φύσω, ἔφυσα", "produrre, generare, mettere fuori; (aor II) ἔφυν far crescere, pf. πέφυκα essere per natura"),
("χαίρω, χαιρήσω, κεχάρηκα, κεχάρημαι, ἐχάρην", "essere lieto, gioire a (+dat), godere a (+participio); χαῖρε, (pl.) χαίρετε salve a tutti"),
("χράομαι, χρήσομαι, ἐχρησάμην, κέχρημαι, ἐχρήσθην", "usare (+dat); trattare qualcuno in un certo modo (+dat e avverbio)"),
("χρή, (imperfetto) χρῆν/ἐχρῆν, (infinito) χρῆναι", "essere necessario (+infinito o +acc e infinito)"),
]

DCC500_NOMI = [
("ἀγών, ἀγῶνος, ὁ", "piazza; lotta; processo"),
("ἀδελφός, –οῦ, ὁ", "fratello"),
("αἷμα, αἵματος, τό", "sangue"),
("αἰτία, αἰτίας, ἡ", "causa; colpa; accusa"),
("ἀλήθεια, ἀληθείας, ἡ", "verità"),
("ἀνάγκη, ἀνάγκης, ἡ", "necessità"),
("ἄνθρωπος, –ου, ὁ/ἡ", "essere umano"),
("ἀνήρ, ἀνδρός, ὁ", "uomo, marito"),
("ἀργύριον, ἀργυρίου, τό", "argento, d'argento; soldi"),
("ἀρετή, ἀρετῆς, ἡ", "eccellenza; virtù; valore militare, coraggio"),
("ἀριθμός, –οῦ, ὁ", "numero"),
("ἀρχή, ἀρχῆς, ἡ", "inizio, origine; comando"),
("βασιλεύς, βασιλέως, ὁ", "re"),
("βίος, βίου, ὁ", "vita"),
("βουλή, βουλῆς, ἡ", "volontà, determinazione; consiglio"),
("βοῦς, βοός, ὁ/ἡ", "toro, bue, mucca"),
("γένος, γένους, τό", "razza, famiglia; genere, classe"),
("γῆ, γῆς, ἡ", "terra, territorio"),
("γνώμη, γνώμης, ἡ", "pensiero, sentenza, proverbio"),
("γλῶσσα, γλώσσης, ἡ", "lingua; linguagio"),
("γράμμα, γράμματος, τό", "lettera, carattere; (plur) uno scritto, documenti"),
("γραφή, γραφῆς, ἡ", "disegno, pittura, documento scritto; atto di accusa scritto"),
("γυνή, γυναικός, ἡ", "donna, moglie"),
("δίκη, δίκης, ἡ", "giustizia; processo"),
("δαίμων, δαίμονος, ὁ/ἡ", "spirito, dio, demone"),
("δεσπότης, –ου, ὁ", "padrone di casa; sovrano assoluto"),
("διαφορά, –ᾶς, ἡ", "differenza; disaccordo"),
("δοῦλος, δούλου, ὁ", "schiavo"),
("δόξα, δόξης, ἡ", "opinione, apparenza; fama, onore gloria"),
("δύναμις, δυνάμεως, ἡ", "potenza; esercito"),
("δῆμος, δήμου, ὁ", "popolo; distretto (opp. πόλις)"),
("ἔθνος, ἔθνους, τό", "nazione"),
("ἐλπίς, ἐλπίδος, ἡ", "speranza; previsione"),
("εἶδος, εἴδους, τό", "forma, aspetto; specie, classe, genere"),
("εἰκός, εἰκότος, τό", "somiglianza, probabilità; εἰκός (ἐστι) è probabile che (+infinito) →ἔοικα"),
("εἰρήνη, εἰρήνης, ἡ", "pace"),
("ἐπιστήμη –ης, ἡ", "conoscenza, scienza, sapere; abilità, perizia"),
("ἔπος, ἔπους, τό", "parola, racconto, favola; profezia"),
("ἔργον, ἔργου, τό", "opera, impresa, lavoro"),
("ἔτος, ἔτους, τό", "anno"),
("ἡγεμών, ἡγεμόνος, ὁ", "guida, comandante, condottiero"),
("ἡδονή, –ῆς, ἡ", "piacere, godimento"),
("ἥλιος, ἡλίου, ὁ", "sole"),
("ἡμέρα, ἡμέρας, ἡ", "giorno"),
("ζῷον, ζῴου, τό", "essere vivente; animale"),
("θάλασσα, θαλάσσης, ἡ", "il mare"),
("θάνατος, θανάτου, ὁ", "morte"),
("θεός,θεοῦ, ὁ/ἡ", "dio, dea"),
("θυγάτηρ, θυγατρός, ἡ", "figlia"),
("θυμός, θυμοῦ, ὁ", "vita; sentimento, volontà; pensiero; animo, desiderio"),
("ἱππεύς, ἱππέως, ὁ", "cavaliere"),
("ἵππος, ἵππου, ὁ", "cavallo"),
("καιρός, καιροῦ, ὁ", "misura giusta; tempo giusto; opportunità, occasione; circostanza"),
("κεφαλή, –ῆς, ἡ", "testa"),
("κίνδυνος, κινδύνου, ὁ", "pericolo, rischio"),
("κόσμος, κόσμου, ὁ", "ordine; decoro, decenza, dignità; mondo, ordine, cosmico, universo"),
("κύκλος, κύκλου, ὁ", "cerchio; sfera; movimento circolare"),
("κύριος, κυρίου, ὁ", "che ha potere; padrone"),
("λαός, λαοῦ, ὁ", "popolo; folla"),
("λίθος, λίθου, ὁ", "pietra"),
("λόγος, λόγου, ὁ", "parola; discorso; ragionamento"),
("μάρτυς, μάρτυρος, ὁ/ἡ", "testimone"),
("μάχη, μάχης, ἡ", "battaglia"),
("μέγεθος, μεγέθους, τό", "grandezza, statura, altezza"),
("μέρος, μέρους, τό", "parte; incarico; situazione"),
("μήτηρ, μητρός, ἡ", "madre"),
("ναός (νεώς), ναοῦ (νεώ), ὁ", "tempio"),
("ναῦς, νεώς, ἡ", "nave"),
("νίκη, νίκης, ἡ", "vittoria"),
("νόμος, νόμου, ὁ", "legge; costume, tradizione"),
("νόσος, νόσου, ὁ", "malattia, infermità; follia"),
("νοῦς (νόος), νοῦ (νόου), ὁ", "mente; intelligenza; perspicacia"),
("νῆσος, νήσου, ἡ", "isola"),
("νύξ, νυκτός, ἡ", "notte"),
("ξένος, ξένου, ὁ", "ospite; straniero"),
("ὁδός, ὁδοῦ, ἡ", "via, strada"),
("οἰκία, οἰκίας, ἡ", "casa"),
("οἶκος, οἴκου, ὁ", "casa; famiglia"),
("ὄνομα, ὀνόματος, τό", "nome; fama"),
("ὄρος, ὄρους, τό", "montagna, collina"),
("ὅπλον, ὅπλου, τό", "arma, utensile; armatura (al plurale)"),
("ὀφθαλμός, –οῦ, ὁ", "occhio"),
("οὐρανός, –οῦ, ὁ", "cielo"),
("οὐσία, οὐσίας, ἡ", "essenza; sostanza; l'essere"),
("πάθος, πάθους, τό", "esperienza, prova, congiuntura; sofferenza, sciagura; passione, commozione; stato, condizione"),
("πατήρ, πατρός, ὁ", "padre"),
("πατρίς, πατρίδος, ἡ", "(agg) patrio, degli avi"),
("παῖς, παιδός, ὁ/ἡ", "fanciullo, figlio, figlia; schiavo"),
("πίστις, πίστεως, ἡ", "fiducia, confidenza; ciò che dà confidenza, garanzia, fede"),
("πλῆθος, πλήθους, τό", "quantità, moltitudine, folla"),
("πνεῦμα, πνεύματος, τό", "soffio, wind, breath, spirit"),
("ποιητής, –οῦ, ὁ", "creatore, poeta"),
("πολιτεία, –ας, ἡ", "costituzione; governo; città"),
("ποταμός, –οῦ, ὁ", "fiume"),
("πούς, ποδός, ὁ", "piede"),
("πόλεμος, πολέμου, ὁ", "guerra"),
("πόλις, πόλεως, ἡ", "città, città-stato"),
("πόνος, πόνου, ὁ", "fatica, lavoro; sforzo, travaglio, pena"),
("πρᾶγμα, πράγματος, τό", "fatto, azione, impresa, cosa"),
("πρᾶξις, πράξεως, ἡ", "azione; affare; impresa"),
("πρέσβυς, πρέσβεως, ὁ", "il vecchio; (al plurale) ambasciatori"),
("πρόσωπον, προσώπου, τό", "faccia, volto; personaggio, persona"),
("πῦρ, πυρός, τό", "fuoco"),
("σημεῖον, σημείου, τό", "segno; segnale; contrassegno"),
("στάδιον, σταδίου, τό (al plurale στάδια e στάδιοι)", "stadio, unità di misura lineare 185 metri"),
("στόμα, στόματος, τό", "bocca; faccia; entrata"),
("στρατηγός, –οῦ, ὁ", "condottiero, comandante, generale"),
("στρατιά, –ᾶς, ἡ", "esercito, armata"),
("στρατιώτης, –ου, ὁ", "soldato"),
("στρατός, –οῦ, ὁ", "esercito"),
("συμφορά, –ᾶς, ἡ", "evento, circostanza, disgrazia"),
("σχῆμα, σχήματος, τό", "figura; forma; aspetto; maniera"),
("σωτηρία, σωτηρίας, ἡ", "salvezza; protezione; considerazione"),
("σῶμα, σώματος, τό", "corpo, cadavere"),
("τάξις,τάξεως, ἡ", "ordine; ordinamento; corpo d'armata"),
("τέκνον, τέκνου, τό", "figlio"),
("τέλος, τέλους, τό", "fine; compimento; esito"),
("τέχνη, τέχνης, ἡ", "arte, abilità"),
("τεῖχος, τείχους, τό", "muro"),
("τιμή, τιμῆς, ἡ", "onore, stima; prezzo, valore; carica, magistratura"),
("τρόπος, τρόπου, ὁ", "modo, maniera, foggia; indole; abitudine, costume"),
("τροφή, τροφῆς, ἡ", "nutrimento, cibo"),
("τόπος, τόπου, ὁ", "luogo"),
("τύχη, τύχης, ἡ", "fortuna (buona o cattiva); fato; possibilità"),
("ὕδωρ, ὕδατος, τό", "acqua"),
("υἱός, υἱοῦ, ὁ", "figlio"),
("φωνή, φωνῆς, ἡ", "voce; suono"),
("φόβος, φόβου, ὁ", "paura; fuga"),
("φύσις, φύσεως, ἡ", "natura"),
("φῶς, φωτός, τό", "luce, luce del giorno"),
("χάρις, χάριτος, ἡ", "grazia, bellezza; piacere, gioia; beneficio, favore;"),
("χείρ, χειρός, ἡ", "mano"),
("χρόνος, χρόνου, ὁ", "tempo"),
("χρῆμα, χρήματος, τό", "cosa utile; (di solito al plurale) beni, proprietà, soldi"),
("χωρίον, χωρίου, τό", "luogo; località; regione"),
("χώρα, χώρας, ἡ", "regione; territorio"),
("ψυχή, ψυχῆς, ἡ", "anima, soffio vitale"),
]

DCC500_AGGETTIVI = [
("αἰσχρός, –ά, –όν", "turpe, brutto"),
("αἴτιος, αἰτία, αἴτιον", "colpevole, responsabile"),
("ἀγαθός, –ή, –όν", "buono, virtuoso, coraggioso, nobile"),
("ἀδύνατος, –ον", "impotente; impossibile"),
("ἀκριβής, –ές", "esatto; preciso; diligente"),
("ἀληθής, –ές", "vero"),
("ἀλλήλων, –οις", "(al plurale solo i casi obliqui) l'un l'altro"),
("ἀμείνων, ἄμεινον", "migliore, più forte, più virtuoso (comparativo di ἀγαθός)"),
("ἀμφότερος, ἀμφοτέρα, ἀμφότερον", "entrambi"),
("ἄδικος, ἄδικον", "ingiusto"),
("ἄλλος, ἄλλη, ἄλλο", "altro"),
("ἄξιος, ἀξία, ἄξιον", "di valore; degno"),
("ἅπας, ἅπασα, ἅπαν", "tutto quanto"),
("ἄριστος, ἀρίστη, ἄριστον", "il meglio, il più virtuoso (superlativo di ἀγαθός)"),
("αὐτός, αὐτή, αὐτό", "[ipse, is, ille, hic, idem] quello stesso (enfasi); lo stesso (con l'articolo); (pron) egli, ella, esso (casi obliqui)"),
("βάρβαρος, –ον", "barbaro; non Greco, straniero"),
("βαρύς, βαρεῖα, βαρύ", "grave, pesante; molesto"),
("βελτίων, βέλτιον", "meglio (comparativo di ἀγαθός)"),
("βραχύς, βραχεῖα, βραχύ", "corto, breve"),
("δέκα", "dieci"),
("δέκατος, –η, –ον", "decimo"),
("δίκαιος, δικαία, δίκαιον", "giusto"),
("δεινός, –ή, –όν", "terribile; esperto, esperto in/a (+infinito)"),
("δεύτερος, –α, –ον", "secondo"),
("δῆλος, δήλη, δῆλον", "visibile; chiaro, manifesto"),
("δυνατός, –ή, –όν", "forte, potente; capace, idoneo"),
("δύο", "due"),
("ἑαυτοῦ, ἑαυτῆς, ἑαυτοῦ", "se stesso (pronome riflessivo)"),
("ἕβδομος, –η, –ον", "settimo"),
("εἰκοστός, –ή, –όν", "ventesimo"),
("εἴκοσι(ν)", "venti"),
("εἷς, μία, ἕν", "uno"),
("ἐγώ, ἐμοῦ, (plur) ἡμεῖς, ἡμῶν", "io, noi"),
("ἕκαστος, ἑκάστη, ἕκαστον", "ciascuno"),
("ἑκάτερος, ἑκατέρα, ἑκάτερον", "each (of two)"),
("ἑκατοστός, –ή, –όν", "centesimo"),
("ἑκατόν", "cento"),("ἐκεῖνος, ἐκείνη, ἐκεῖνον", "quello, quella, quella cosa; ἐκεῖνος... οὗτος quello... questo"),
("ἕκτος, –η, –ον", "sesto"),
("ἐλάσσων, ἔλασσον", "più piccolo, meno (comparativo di μικρός)"),
("ἐλεύθερος, ἐλευθέρα, ἐλεύθερον", "libero"),
("ἐμός, ἐμή, ἐμόν", "mio"),
("ἔνατος, –α, –ον", "nono"),
("ἐννέα", "nove"),
("ἕξ", "sei"),
("ἑπτά", "sette"),
("ἕτερος, ἑτέρα, ἕτερον", "altro (di due); solitario; privo, mancante"),
("εὐθύς, εὐθεῖα, εὐθύ", "diritto; diretto; (avv) immediatamente"),
("ἐχθρός, –ά, –όν", "avverso, nemico; ostile a (+dat)"),
("ἡδύς, ἡδεῖα, ἡδύ", "dolce, soave"),
("ἡμέτερος, ἡμετέρα, ἡμέτρον", "nostro"),
("ἥσσων, ἧσσον", "minore, più debole (comparativo di κακός o μικρός)"),
("θεῖος, θεία, θεῖον", "divino"),
("ἰσχυρός, –ά, –όν", "forte"),
("ἱερός, –ά, –όν", "sacro"),
("ἱκανός, –ή, –όν", "sufficente; competente, abile a (+infinito)"),
("ἴδιος, ἰδία, ἴδιον", "proprio, peculiare"),
("ἴσος, ἴση, ἴσον", "uguale, lo stesso di (+dat)"),
("κακός, –ή, –όν", "cattivo, vile"),
("καλός, –ή, –όν", "bello"),
("κοινός, –ή, –όν", "comune"),
("κρείσσων, κρεῖσσον", "più forte, più potente; migliore, più virtuoso (comp of ἀγαθός)"),
("λαμπρός, –ά, –όν", "splendido, brillante; celebre, illustr"),
("λοιπός, –ή, –όν", "rimanente"),
("μέγας, μεγάλη, μέγα", "grande, grande cosa"),
("μέσος, μέση, μέσον", "mezzo, mediano; τὸ μέσον il mezzo"),
("μακρός, –ά, –όν", "lungo, alto; ampio, grande; abbondante"),
("μηδείς, μηδεμία, μηδέν", "nessuno, nulla"),
("μικρός, –ά, –όν", "piccolo"),
("μόνος, μόνη, μόνον", "solo"),
("μυρίος, μυρία, μυρίον", "innumerevole; μύριοι 10,000; μυριάς -άδος ἡ 10,000, un innumerevole ammontare"),
("νέος, νέα, νέον", "nuovo; giovane"),
("οἰκεῖος, οἰκεία, οἰκεῖον", "domestico, della casa; dei propri beni; adatto, conveniente"),
("οἷος, οἵα, οἷον", "quale, di che specie, come, (esclamativo) che...!, come...! ; οἷός τε (+infinito) adatto o capace di; οἷόν τε (+infinito) è possibile..."),
("οὐδείς, οὐδεμία, οὐδέν", "nessuno, nulla"),
("οὗτος, αὕτη, τοῦτο", "questo, questi; μετὰ ταῦτα dopo questo"),
("ὀκτώ", "otto"),
("ὀλίγος, ὀλίγη, ὀλίγον", "piccolo, poco"),
("ὀξύς, ὀξεῖα, ὀξύ", "acuto, aguzzo; penetrante"),
("ὀρθός, –ή, –όν", "upright, straight, true, regular"),
("ὄγδοος, –η, –ον", "ottavo"),
("ὅδε, ἥδε, τόδε", "questo, questa"),
("ὅλος, ὅλη, ὅλον", "tutto quanto, intero"),
("ὅμοιος, ὁμοία, ὅμοιον", "simile, uguale (+dat)"),
("ὅς, ἥ, ὅ", "chi, il quale"),
("ὅσος, ὅση, ὅσον", "quanto; (al pl.) tanti quanti; ὅσον (avv) tanto quanto"),
("ὅσπερ, ἥπερ, ὅπερ", "il quale a dire il vero"),
("ὅστις, ἥτις, ὅτι", "chiunque, qualunque cosa; (in domande indirette) chi, che cosa"),
("πέντε", "cinque"),
("παλαιός, –ά, –όν", "vecchio, antico"),
("πεμπτός, –ή, –όν", "quinto"),
("πλέων, πλέον", "di più, più grande (comparativo di πολύς)"),
("πλεῖστος, πλείστη, πλεῖστον", "il più grande (superlativo di πολύς)"),
("πολέμιος, πολεμία, πολέμιον", "nemico; οἱ πολέμιοι il nemico"),
("πολύς, πολλή, πολύ", "molto, tanto; ὡς ἐπὶ τὸ πολύ per la maggior parte"),
("πονηρός, –ά, –όν", "malvagio"),
("ποῖος, ποία, ποῖον", "di che natura?"),
("πότερος, ποτέρα, πότερον", "quale dei due? πότερον se"),
("ποῦ", "dove"),
("πρότερος, προτέρα, πρότερον", "precedente, anteriore; τὸ πρότερον il precedente"),
("πρῶτος, πρώτη, πρῶτον", "primo; (avv) τὸ πρῶτον al primo posto"),
("πᾶς, πᾶσα, πᾶν", "tutto; ogni"),
("ῥᾴδιος, ῥᾳδία, ῥᾴδιον", "facile"),
("σαφής, σαφές", "chiaro, manifesto; certo"),
("σοφός, –ή, –όν", "sapiente"),
("σός, σή, σόν", "tuo, tuoi (sing.; ὑμέτερος = plur.)"),
("σύ, σοῦ, (plur) ὑμεῖς, ὑμῶν", "tu, voi"),
("σύμμαχος, –ον", "alleato con (+dat); οἱ σύμμαχοι gli alleati"),
("τέταρτος, –η, –ον", "quarto"),
("τέτταρες, τέτταρα", "quattro"),
("τίς, τί", "chi? cosa? quale? (pron./agg. interrogativo)"),
("ταχύς, ταχεῖα, ταχύ", "veloce; (avv) τάχα velocemente; forse"),
("τις, τι", "qualcuno, qualcosa (pron./agg. indefinito enclitico)"),
("τοιοῦτος, τοιαύτη, τοιοῦτο", "tale, siffatto"),
("τοιόσδε, τοιάδε, τοιόνδε", "tale (come questo), di tale origine (come questo)"),
("τοσοῦτος, τοσαύτη, τοσοῦτο(ν)", "così grande"),
("τρίτος, –η, –ον", "terzo"),
("τρεῖς, τρία", "tre"),
("τριάκοντα", "trenta"),
("τριακοστός, –ή, –όν", "trentesimo"),
("ὑμέτερος, ὑμετέρα, ὑμέτερον", "vostro, vostri (plur.; σός = sing.)"),
("ὕστερος, ὑστέρα, ὕστερον", "che viene dopo, seguente (+gen); prossimo, più tardo; (avv) ὕστερον più tardi, poi"),
("φίλος, φίλη, φίλον", "amico; caro"),
("φανερός, –ά, –όν", "evidente, manifesto; famoso"),
("χαλεπός, –ή, –όν", "difficile; intrattabile"),
("χαλκοῦς, –ῆ, –οῦν", "bronzeo, di bronzo"),
("χείρων, χεῖρον", "peggiore, inferiore (comparativo. di κακός)"),
("χρήσιμος, χρησίμη, χρήσιμον", "utile"),
]

DCC500_MISC = [
("ἀεί", "sempre", "avverbio"),
("ἀλλά", "ma", "congiunzione: coordinativa"),
("ἀμφί", "a causa (+gen); intorno, presso (+dat, +acc); ", "preposizione"),
("ἀνά", "sopra, su (+gen, +dat, +acc); per, attraverso (+gen, +dat, +acc)", "preposizione"),
("ἀντί", "di fronte, contro (+gen)", "preposizione"),
("ἄλλως", "altrimenti", "avverbio"),
("ἁπλῶς", "simply, singly, in one way", "avverbio"),
("ἀπό", "da (+gen)", "preposizione"),
("ἅμα", "insieme; mentre; (prep.) insieme con (+dat)", "avverbio"),
("ἄν", "[segna il verbo come potenziale (con ottativo), o eventuale (con congiuntivo)]", "avverbio"),
("ἄνευ", "senza (+gen)", "preposizione"),
("ἄνω", "su, in alto", "avverbio"),
("ἄρα", "allora, quindi [introduce un'inferenza]", "avverbio"),
("ἆρα", "e non?, forse? [introduce una domanda]", "avverbio"),
("αὐτίκα", "subito, immediatamente", "avverbio"),
("αὖ, αὖθις", "inoltre; d'altra parte; un'altra volta (ancora)", "avverbio"),
("γάρ", "perché (esplicativo), davvero, infatti (confermativo)", "congiunzione: coordinativa"),
("γε", "(enclitica) appunto, invero; almeno", "avverbio"),
("δέ", "e; ma", "congiunzione: coordinativa"),
("δή", "certamente, certo, infatti, davvero (enfatico, da maggiore esattezza)", "avverbio"),
("διά", "attraverso (+gen); per mezzo di (+acc)", "preposizione"),
("ἐάν (εἰ-ἄν)", "se (+cong)", "congiunzione: subordinativa"),
("εἰ", "se (+indic, +ott); εἴπερ se davvero", "congiunzione: subordinativa"),
("εἰς", "in, verso (+acc)", "preposizione"),
("εἶτα", "poi, in seguito; quindi", "avverbio"),
("εἴτε…εἴτε", "sia che... sia che", "congiunzione: coordinativa"),
("ἐκ, ἐξ", "da, fuori (+gen)", "preposizione"),
("ἐκεῖ", "là", "avverbio"),
("ἐν", "in, dentro, tra (+dat)", "preposizione"),
("ἐναντίος ἐναντία ἐναντίον", "di fronte, contro (+gen)", "preposizione"),
("ἕνεκα", "a causa di, al fine di (+gen)", "preposizione"),
("ἔνθα", "lì, là", "avverbio"),
("ἐνταῦθα", "qui; lì (+gen)", "avverbio"),
("ἔξω", "fuori, eccetto (+gen)", "avverbio e preposizione"),
("ἐπεί", "dopo; quando", "congiunzione: subordinativa"),
("ἔπειτα", "poi, in seguito", "avverbio"),
("ἐπί", "sopra, a, presso (+gen); sopra, su (+dat); sopra, verso (+acc)", "preposizione"),
("ἔτι", "ancora, inoltre", "avverbio"),
("εὖ", "bene (opp. κακῶς); giustamente, felicemente, fortunatamente", "avverbio"),
("ἕως", "finché; mentre", "congiunzione: subordinativa"),
("ἤ", "o, oppure; che (dopo un comparativo); ἤ...ἤ o...o", "congiunzione: coordinativa"),
("ἦ", "certo, senza dubbio (enfatizza quello che segue)", "avverbio"),
("ἤδη", "già (tempo passato); ora, già (tempo presente); ormai, subito (tempo futuro)", "avverbio"),
("ἵνα", "affinché, per (+cong, +ott); dove (avverbio di luogo +indic)", "congiunzione: subordinativa"),
("ἴσως", "ugualmente, allo stesso modo; forse, probabilmente", "avverbio"),
("καί", "e, anche, pure; καί...καί e...e, non solo...ma anche...", "congiunzione: coordinativa"),
("καίτοι (καί-τοι)", "certo, a dire il vero", "avverbio"),
("κἄν (καὶ-ἄν)", "anche se (+cong)", "congiunzione: subordinativa"),
("κατά", "giù, giù da (+gen), per (+gen, tempo) su, sopra, durante (+acc); κατὰ γῆν via terra; κατὰ φύσιν secondo natura; κατ’ ἔθνη attraverso i territori; καθ᾿ἕνα uno alla volta", "preposizione"),
("μάλα", "molto, assai", "avverbio"),
("μάλιστα", "most, most of all; (in replies) certainly", "avverbio"),
("μᾶλλον", "di più, piuttosto; μᾶλλον...ἤ piuttosto che", "avverbio"),
("μέν...δέ", "da una parte...dall'altra; μέν (da solo) davvero", "congiunzione: coordinativa"),
("μέντοι", "however; of course", "avverbio"),
("μέχρι (+gen)", "finché; fino a (prep. +gen)", "congiunzione: subordinativa"),
("μή", "non (negativo per il congiuntivo e il periodo ipotetico); εἰ μή se non, eccetto", "congiunzione: subordinativa"),
("μήν", "certo [enfatizza la particella precedente]", "avverbio"),
("μήτε...μήτε", "né...né", "congiunzione: coordinativa"),
("μετά", "con (+gen); in mezzo, dopo (+acc)", "preposizione"),
("μεταξύ", "in mezzo", "avverbio"),
("μηδέ", "e non", "congiunzione: coordinativa"),
("μόνον", "solo", "avverbio"),
("ναί", "davvero, si (usato in affermazioni forti)", "avverbio"),
("νῦν, νυνί", "ora", "avverbio"),
("ὁ, ἡ, τό", "il (articolo)", "articolo determinativo"),
("ὅθεν", "da dove, donde", "avverbio"),
("ὅμως", "tuttavia, peraltro; sebbene", "avverbio"),
("ὅπου", "dove; quando; poiché", "congiunzione: subordinativa"),
("ὅπως", "quando; affinché (+cong, +ott)", "congiunzione: subordinativa"),
("ὅταν (ὅτε-ἄν)", "quando, allorché (+cong)", "congiunzione: subordinativa"),
("ὅτε", "quando, allorché (+indic, +ott)", "congiunzione: subordinativa"),
("ὅτι", "perché, che; (col superlativo) al più presto, il più possibile", "congiunzione: subordinativa"),
("οὐ, οὐκ, οὐχ", "non (con verbi all'indicativo)", "avverbio"),
("οὐδέ", "e non, ma non, nemmeno, neppure; οὐδέ...οὐδέ né...né", "congiunzione: coordinativa"),
("οὐκέτι", "no longer, no more", "avverbio"),
("οὐκοῦν", "sicché, perciò (invita a dire di sì a un'affermazione)", "avverbio"),
("οὖν", "dunque, senza dubbio, infatti", "avverbio"),
("οὔτε...οὔτε", "né...né", "congiunzione: coordinativa"),
("οὕτως", "in questo modo, così", "avverbio"),
("πάλιν", "di nuovo; indietro, al contrario", "avverbio"),
("πάντως", "del tutto, assolutamente, in ogni caso", "avverbio"),
("πάνυ", "del tutto, affatto, totalmente", "avverbio"),
("παρά", "da (+gen); presso, accanto (+dat); a, verso, al contrario (+acc)", "preposizione"),
("περ", "assai, proprio; sebbene [enclitica aggiunta a pronomi e altre particelle per enfasi]", "avverbio"),
("περί", "intorno, riguardo a (+gen); presso, per (+dat); lungo, verso (+acc)", "preposizione"),
("πλέον", "più, piuttosto", "avverbio"),
("πλήν", "(preposizione) eccetto, tranne (+gen); (congiunzione) eccetto che, a meno che, ma", "preposizione"),
("πολλάκις", "spesso", "avverbio"),
("ποτε", "(enclitica) quando, i quel tempo, una volta", "avverbio"),
("πότε", "quando?", "avverbio"),
("που", "(enclitica) in qualche luogo; in qualche modo, forse (per precisare un'affermazione)", "avverbio"),
("πρίν", "prima; finché non", "congiunzione: subordinativa"),
("πρό", "prima, davanti (+gen)", "preposizione"),
("πρός", "dalla parte di, innanzi (+gen); presso, su, a in (+dat); a, verso (+acc)", "preposizione"),
("πως", "(enclitica) in qualche modo, come che sia", "avverbio"),
("πῶς", "come?", "avverbio"),
("σύν", "con (+ dat. di compagnia o mezzo)", "preposizione"),
("τε", "e; τε...τε sia...sia", "congiunzione: coordinativa"),
("τοίνυν (τοί-νυν)", "quindi, in accordo con (inferenzale); inoltre, in più (transizionale)", "avverbio"),
("τότε", "allora, in quel tempo; οἱ τότε gli uomini di quel tempo (opposto a οἱ νῦν)", "avverbio"),
("ὑπέρ", "al di là, per (+gen), oltre (+acc)", "preposizione"),
("ὑπό", "sotto (+gen, +dat); da (+gen di agente personale); sotto (+acc moto a luogo)", "preposizione"),
("χωρίς", "separatamente, a parte; (+gen) senza, differentemente", "avverbio"),
("ὦ", "oh! (quando è con il vocativo non è enfatico)", "interiezione"),
("ὧδε", "così, in questo modo; a tal punto; qui", "avverbio"),
("ὡς", "come, nel modo che; affinché (+cong/+ott, introduce una subordinata finale); che (introduce un discorso indiretto)", "congiunzione: subordinativa"),
("ὥσπερ", "come se, finché", "congiunzione: subordinativa"),
("ὥστε", "cosicché, in modo che (introduce una subordinata consecutiva), (con il risultato) che", "congiunzione: subordinativa"),
]

WORDS = (DCC500_VERBI, DCC500_NOMI, DCC500_AGGETTIVI, DCC500_MISC)

DCC500_VERBI_FLAT = []
for verb in DCC500_VERBI:
    verb_pparts = verb[0].split(",")
    for ppart in verb_pparts:
        DCC500_VERBI_FLAT.append((ppart.strip(), verb[1]))
    
ITEMS = (DCC500_VERBI_FLAT, 
         DCC500_NOMI, 
         DCC500_AGGETTIVI, 
         DCC500_MISC,
         DCC500_VERBI_FLAT + DCC500_NOMI,
         DCC500_NOMI + DCC500_AGGETTIVI,
         DCC500_VERBI_FLAT + DCC500_AGGETTIVI,
         DCC500_VERBI_FLAT + DCC500_MISC,
         DCC500_VERBI_FLAT + DCC500_NOMI + DCC500_AGGETTIVI + DCC500_MISC)


MAXQUESTION = 33
MAXSINTAGMI = 300
EXTRA=400

if __name__ == "__main__":
  random.seed()
  with codecs.open('DCC500_LATEST','w', encoding='utf8') as outf:
    
    for set in WORDS:
        print(">>>>START WORDSET>>>>>", file=outf)
        for item in set:
            if set == DCC500_MISC:
                print("%s\t%s\t%s" % item, file=outf)
            else:
                print("%s\t%s" % item, file=outf)
        print(">>>>>>>>END WORDSET>>>>>>>>\n\n", file=outf)
     
    exnum = 1     
    for set in ITEMS:
        # shuffle the list
        random.shuffle(set)
        print(">>>>START EXERCISE %d >>>>>" % (exnum,), file=outf)
        for item in set[:MAXQUESTION]:
            print("%s" % (item[0],), file=outf)
        print(">>>>>>>>END RUN ONE>>>>>>>>\n", file=outf)
        for item in set[MAXQUESTION:2*MAXQUESTION]:
            print("%s" % (item[0],), file=outf)
        print(">>>>>>>>END RUN TWO>>>>>>>>\n\n", file=outf)
        for item in set[2*MAXQUESTION:3*MAXQUESTION]:
            print("%s" % (item[0],), file=outf)
        print(">>>>>>>>END RUN THREE>>>>>>>>\n\n", file=outf)
        
        exnum += 1
        
    # ora il generatore di sintagmi per i participi
    TEMPI_PARTICIPIO = ['PRESENTE.PARTICIPIO.ATTIVO',
        'FUTURO.PARTICIPIO.ATTIVO',
        'AORISTO.PARTICIPIO.ATTIVO',
        'PERFETTO.PARTICIPIO.ATTIVO',
        'PRESENTE.PARTICIPIO.MEDIO',
        'FUTURO.PARTICIPIO.MEDIO',
        'AORISTO.PARTICIPIO.MEDIO',
        'PERFETTO.PARTICIPIO.MEDIO',
        'FUTUROPERFETTO.PARTICIPIO.PASSIVO',
        'FUTURO.PARTICIPIO.PASSIVO',
        'AORISTO.PARTICIPIO.PASSIVO',
        ]
    
    GENERE = ['MASCHILE', 'FEMMINILE', 'NEUTRO']
    NUMERO = ['SINGOLARE', 'PLURALE', 'DUALE']
    CASO = ['NOMINATIVO', 'GENITIVO', 'DATIVO', 'ACCUSATIVO']
    FUNZIONE = ['TEMPORALE', 
                'CAUSALE', 
                'MODALE O STRUMENTALE', 
                'FINALE', 
                'CONDIZIONALE (PROTASI)', 
                'CONCESSIVA', ]

    print(">>>>START EXERCISE PARTICIPLE >>>>>\n", file=outf)
    exnum = 1
    print("ESERCIZIO_NUMERO\tPARTICIPIO_GRECO\tTRADUZIONE_ITALIANA\tVERBO_DA_CONIUGARE\tVOCE_DI_CONIUGAZIONE_RICHIESTA\tIN_FUNZIONE", file=outf)
       
    for counter in range(MAXSINTAGMI):
        verb = random.choice(DCC500_VERBI)
        time = random.choice(TEMPI_PARTICIPIO)
        gender = random.choice(GENERE)
        number = random.choice(NUMERO)
        case = random.choice(CASO)
        func = random.choice(FUNZIONE)
        
        print("P%03d\t%s+++\tIN FUNZIONE: %s\t%s (%s)\t%s\t%s" % (exnum, verb[0].split(',')[0], func, verb[0], verb[1], time + ' ' + case + '.' + gender + '.' + number, func), file=outf)
        exnum += 1
    print(">>>>>>>>END EXERCISE PARTICIPLE >>>>>>>>>\n\n", file=outf)   

    # ora il generatore di sintagmi per i verbi
    TEMPI = ['PRESENTE.INDICATIVO.ATTIVO',
        'IMPERFETTO.INDICATIVO.ATTIVO',
        'FUTURO.INDICATIVO.ATTIVO',
        'AORISTO.INDICATIVO.ATTIVO',
        'PERFETTO.INDICATIVO.ATTIVO',
        'PIUCCHEPERFETTO.INDICATIVO.ATTIVO',
        'PRESENTE.CONGIUNTIVO.ATTIVO',
        'AORISTO.CONGIUNTIVO.ATTIVO',
        'PERFETTO.CONGIUNTIVO.ATTIVO',
        'PRESENTE.OTTATIVO.ATTIVO',
        'FUTURO.OTTATIVO.ATTIVO',
        'AORISTO.OTTATIVO.ATTIVO',
        'PERFETTO.OTTATIVO.ATTIVO',
        'PRESENTE.IMPERATIVO.ATTIVO',
        'AORISTO.IMPERATIVO.ATTIVO',
        'PRESENTE.INFINITO.ATTIVO',
        'FUTURO.INFINITO.ATTIVO',
        'AORISTO.INFINITO.ATTIVO',
        'PERFETTO.INFINITO.ATTIVO',
        'PRESENTE.INDICATIVO.MEDIO',
        'IMPERFETTO.INDICATIVO.MEDIO',
        'FUTURO.INDICATIVO.MEDIO',
        'AORISTO.INDICATIVO.MEDIO',
        'PERFETTO.INDICATIVO.MEDIO',
        'PIUCCHEPERFETTO.INDICATIVO.MEDIO',
        'PRESENTE.CONGIUNTIVO.MEDIO',
        'AORISTO.CONGIUNTIVO.MEDIO',
        'PERFETTO.CONGIUNTIVO.MEDIO',
        'PRESENTE.OTTATIVO.MEDIO',
        'FUTURO.OTTATIVO.MEDIO',
        'AORISTO.OTTATIVO.MEDIO',
        'PERFETTO.OTTATIVO.MEDIO',
        'PRESENTE.IMPERATIVO.MEDIO',
        'AORISTO.IMPERATIVO.MEDIO',
        'PERFETTO.IMPERATIVO.MEDIO',
        'PRESENTE.INFINITO.MEDIO',
        'FUTURO.INFINITO.MEDIO',
        'AORISTO.INFINITO.MEDIO',
        'PERFETTO.INFINITO.MEDIO',
        'FUTURO.INDICATIVO.PASSIVO',
        'AORISTO.INDICATIVO.PASSIVO',
        'FUTUROPERFETTO.INDICATIVO.PASSIVO',
        'AORISTO.CONGIUNTIVO.PASSIVO',
        'FUTURO.OTTATIVO.PASSIVO',
        'AORISTO.OTTATIVO.PASSIVO',
        'FUTUROPERFETTO.OTTATIVO.PASSIVO',
        'AORISTO.IMPERATIVO.PASSIVO',
        'FUTURO.INFINITO.PASSIVO',
        'AORISTO.INFINITO.PASSIVO',
        'FUTUROPERFETTO.INFINITO.PASSIVO',
        ]
    PERSONA = ['PRIMA', 'SECONDA', 'TERZA']
    
    print(">>>>START EXERCISE VERB >>>>>\n", file=outf)
    exnum = 1
    print("ESERCIZIO_NUMERO\tVERBO_GRECO\tTRADUZIONE_ITALIANA\tVERBO_DA_CONIUGARE\tVOCE_DI_CONIUGAZIONE_RICHIESTA", file=outf)
       
    for counter in range(MAXSINTAGMI+EXTRA):
        if exnum > MAXSINTAGMI:
            break
        verb = random.choice(DCC500_VERBI)
        time = random.choice(TEMPI+TEMPI_PARTICIPIO)
        person = random.choice(PERSONA)
        number = random.choice(NUMERO)

        if (person == "PRIMA" and number == "DUALE"):
            continue
        elif ('IMPERATIVO' in time and person in ['PRIMA',]):
            continue
        elif ('INFINITO' in time and (person in ['SECONDA', 'TERZA'] or number in ['PLURALE', 'DUALE'])):
            continue
        elif ('PARTICIPIO' in time and (person in ['SECONDA', 'TERZA'] or number in ['PLURALE', 'DUALE'])):
            continue    
        else:
            print("V%03d\t%s+++\t<TRADUZIONE>\t%s (%s)\t%s" % (exnum, verb[0].split(',')[0], verb[0], verb[1], time + ' ' + person + '_PERSONA.' + number), file=outf)
            exnum += 1
    print(">>>>>>>>END EXERCISE VERB >>>>>>>>>\n\n", file=outf)   
        
        
    