#! /usr/bin/env python"),
# -*- coding: utf-8 -*-"),

import random
import codecs


DCC500_VERBI = [
("ἀγγέλλω, ἀγγελῶ, ἤγγειλα, ἤγγελκα, ἤγγελμαι, ἠγγέλθην", "annunciare"),
("ἄγω, ἄξω, ἤγαγον, ἦχα, ἦγμαι, ἤχθην", "condurre, portare"),
("ἀδικέω, ἀδικήσω, ἠδίκησα, ἠδίκηκα, ἠδίκημαι, ἠδικήθην", "operare ingiustamente; maltrattare"),
("αἱρέω, αἱρήσω, 2 aor. εἷλον, ᾕρηκα, ᾕρημαι, ᾑρέθην", "prendere; espugnare; (al medio) scegliere"),
("αἴρω, ἀρῶ, ἦρα, ἦρκα, ἦρμαι, ἤρθην", "sollevare"),
("αἰσθάνομαι, αἰσθήσομαι, 2 aor. ᾐσθόμην, ᾔσθημαι", "percepire, sentire; comprendere"),
("αἰτέω, αἰτήσω, ᾔτησα, ᾔτηκα, ᾔτημαι, ᾐτήθην", "domandare; desiderare"),
("ἀκούω, ἀκούσομαι, ἤκουσα, ἀκήκοα, plup. ἠκηκόη or ἀκηκόη, ἠκούσθην", "sentire; ascoltare"),
("ἁλίσκομαι, ἁλώσομαι, 2 aor. ἑάλων, ἑάλωκα", "essere preso, conquistato (all'attivo si usa αἱρέω)"),
("ἁμαρτάνω, ἁμαρτήσομαι, ἡμάρτησα, 2 aor. ἥμαρτον, ἡμάρτηκα, ἡμάρτημαι, ἡμαρτήθην", "non cogliere, fallire (+gen); sbagliare, rendersi colpevole, peccare"),
("ἀναιρέω, ἀναιρήσω, ἀνεῖλον, ἀνῄρηκα, ἀνῄρημαι, ἀνῃρέθην", "distruggere; sollevare; dare un responso"),
("ἀξιόω, ἀξιώσω, ἠξίωσα, ἠξίωκα, ἠξίωμαι, ἠξιώθην", "ritenere giusto, ritenere degno"),
("ἀπαλλάσσω, ἀπαλλάξω, ἀπήλλαξα, ἀπήλλαχα, ἀπήλλαγμαι, ἀπηλλάχθην or ἀπηλλάγην", "cambiare; (al medio) liberarsi di"),
("ἀποδίδωμι, ἀποδώσω, ἀπέδωκα, ἀποδέδωκα, ἀποδέδομαι, ἀπεδόθην", "restituire; permettere; (al medio) vendere"),
("ἀποθνῄσκω, ἀποθανοῦμαι, 2 aor. ἀπέθανον, ἀποτέθνηκα", "morire"),
("ἀποκρίνω, ἀποκρινῶ, ἀπεκρινάμην, ἀπεκρίθη", "separare, scegliere; (al medio) rispondere"),
("ἀποκτείνω, ἀποκτενῶ, ἀπέκτεινα, ἀπέκτονα", "uccidere"),
("ἀπόλλυμι, ἀπολῶ, ἀπώλεσα, 2 aor. medio ἀπωλόμην, perf. ἀπολώλεκα (“ho distrutto completamente”) o ἀπόλωλα (“sono annullato”)", "distruggere; (al medio) morire"),
("ἄρχω, ἄρξω, ἦρξα, ἦργμαι, ἤρχθην", "comincio (+gen); conduco, governo (+gen)"),
("ἀφίημι, ἀφήσω, ἀφῆκα, ἀφεῖκα, ἀφεῖμαι, ἀφείθην", "lasciar andare"),
("ἀφαιρέω, ἀφαιρήσω, ἀφεῖλον, ἀφῄρηκα, ἀφῄρημαι, ἀφῃρέθην", "togliere, portare via; separare"),
("ἀφικνέομαι, ἀφίξομαι, 2 aor. ἀφικόμην, ἀφῖγμαι", "arrivare, giungere"),
("βαίνω, βήσομαι, 2 aor. ἔβην, βέβηκα", "camminare, andare, tornare"),
("βάλλω, βαλῶ, 2 aor. ἔβαλον, βέβληκα, βέβλημαι, ἐβλήθην", "lanciare, scagliare, colpire (+acc) con (+dat)"),
("βλέπω, βλέψομαι, ἔβλεψα", "vedere; guardare"),
("βοηθέω, βοηθήσω, ἐβοήθησα, βεβοήθηκα", "aiutare, soccorrere (+dat)"),
("βουλεύω βουλεύσω, ἐβούλευσα, βεβούλευκα, βεβούλευμαι, ἐβουλεύθην", "progettare, decidere; (al medio) consigliarsi, decidere"),
("βούλομαι, βουλήσομαι, βεβούλημαι, ἐβουλήθην", "(+infin.) volere; ὁ βουλόμενος colui al quale piace"),
("γίγνομαι, γενήσομαι, 2 aor. ἐγενόμην, γέγονα, γεγένημαι, ἐγενήθην", "diventare; verificarsi; essere"),
("γιγνώσκω, γνώσομαι, ἔγνων, ἔγνωκα, ἔγνωσμαι, ἐγνώσθην", "conoscere; pensare; decidere"),
("γράφω, γράψω, ἔγραψα, γέγραφα, γέγραμμαι, ἐγράφην", "scrivere"),
("δέδοικα [perfetto con forza di presente], δείσομαι, ἔδεισα", "temere"),
("δεῖ, δεήσει, impf. ἔδει", "si deve, è necessario (+acc e infinito)"),
("δείκνυμι, δείξω, ἔδειξα, δέδειχα, δέδειγμαι, ἐδείχθην", "mostrare, spiegare"),
("δέχομαι, δέξομαι, ἐδεξάμην, δέδεγμαι, -εδέχθην", "ricevere, prendere; accogliere, preferire"),
("δέω, δεήσω, ἐδέησα, δεδέηκα, δεδέημαι, ἐδεήθην", "mancare (+gen)"),
("δηλόω, δηλώσω, ἐδήλωσα, δεδήλωκα, ἐδηλώθην", "mostrare, dichiarare, spiegare"),
("διαφέρω, διοίσω, 1 aor. διήνεγκα, 2 aor. διήνεγκον, διενήνοχα, διενήνεγμαι", "trasportare; spargere; differire; (impers.) διαφέρει fa differenza a (+dat)"),
("διαφθείρω, διαφθερῶ, διέφθειρα, διέφθαρκα, διέφθαρμαι, διεφθάρην", "distruggere; mandare in rovina"),
("διδάσκω, διδάξω, ἐδίδαξα, δεδίδαχα, δεδίδαγμαι, ἐδιδάχθην", "insegnare"),
("δίδωμι, δώσω, ἔδωκα, δέδωκα, δέδομαι, ἐδόθην", "dare"),
("διώκω, διώξομαι, ἐδίωξα, δεδίωχα, ἐδιώχθην", "inseguire; perseguire penalmente"),
("δοκέω, δόξω, ἔδοξα", "pensare (+acc e infinito); sembrare; (impersonale) δοκεῖ μοι mi sembra"),
("δράω, δράσω, ἔδρασα, δέδρακα, δέδραμαι, ἐδράσθην", "fare"),
("δύναμαι, δυνήσομαι, ἐδυνήθην, δεδύνημαι", "(+infinito) potere"),
("ἐάω, ἐάσω, εἴασα", "permettere (+acc e infinito); lasciare, lasciar solo"),
("ἐθέλω, ἐθελήσω, ἠθέλησα, ἠθέληκα", "(+infin) volere; desiderare"),
("εἶδον, 2 aor. di ὁράω, infin.att. ἰδεῖν, infinito (al medio) ἰδέσθαι", "io vidi"),
("εἰμί, ἔσομαι, impf. ἦν, infin. εἶναι", "essere, esistere"),
("εἶμι, infinito ἰέναι, participio ἰών, ἰοῦσα, ἰόν", "andrò (fut. di ἔρχομαι)"),
("εἶπον", "io dissi, io parlai, 2 aor. → λέγω, φημί"),
("ἐλαύνω, ἐλῶ, ἤλασα, -ελήλακα, ἐλήλαμαι, ἠλάθην", "mettere in moto; avanzare"),
("ἔοικα, participio εἰκώς", "essere simile, sembrare (+dat); convenire"),
("ἕπομαι ἕψομαι, 2 aor. ἑσπόμην", "seguire"),
("ἐργάζομαι, ἐργάσομαι, εἰργασάμην, εἴργασμαι", "lavorare, operare"),
("ἔρομαι, ἐρήσομαι, 2 aor. ἠρόμην", "ask, ask one about (+double acc.)"),
("ἔρχομαι, fut. εἶμι/ἐλεύσομαι, 2 aor. ἦλθον, ἐλήλυθα", "venire"),
("ἐρωτάω, ἐρήσομαι, 2 aor. ἠρόμην", "domandare qualcosa (acc.) a qualcuno (acc.); chiedere"),
("εὑρίσκω, εὑρήσω, 2 aor. ηὗρον/εὗρον, ηὕρηκα or εὕρηκα, εὕρημαι, εὑρέθην", "trovare"),
("ἔχω, ἕξω or σχήσω, 2 aor. ἔσχον, ἔσχηκα, impf. εἶχον", "avere; stare (+avv.)"),
("ἡγέομαι, ἡγήσομαι, ἡγησάμην, ἥγημαι", "guidare; ritenere"),
("ἥκω, ἥξω, pf. ἧκα", "essere giunto"),
("ζάω, ζήσω, ἔζησα, ἔζηκα", "vivere"),
("ζητέω, ζητήσω, ἐζήτησα, ἐζήτηκα", "cercare"),
("θαυμάζω, θαυμάσομαι, ἐθαύμασα, τεθαύμακα, τεθαύμασμαι, ἐθαυμάσθην", "meravigliarsi"),
("θνῄσκω, 2 aor. -έθανον, τέθνηκα, θανοῦμαι", "morire, essere uccisi"),
("θύω, θύσω, ἔθυσα, τέθυκα, τέθυμαι, ἐτύθην", "sacrificare"),
("ἵημι, ἥσω, ἧκα, -εἷκα, εἷμαι, -εἵθην", "mandare; spedire; mettere in moto; (al medio) affrettarsi, correre verso"),
("ἵστημι, στήσω, ἔστησα, 2 aor. ἔστην, ἕστηκα, piuccheperfetto εἱστήκη, ἐστάθην", "collocare; (al medio) stare"),
("καθίστημι, καταστήσω, κατέστησα, κατέστην, καθέστηκα, piuccheperfetto καθειστήκη, κατεστάθην", "disporre, stabilire; portare in un certo stato, rendere"),
("καλέω, καλῶ, ἐκάλεσα, κέκληκα, κέκλημαι, ἐκλήθην", "chiamare, convocare"),
("καταλαμβάνω, καταλήψομαι, κατέλαβον, κατείληφα, κατείλημμαι, κατελήφθην", "afferrare, prendere, arrestare, costringere"),
("κατασκευάζω, κατασκευάσω, κατεσκεύασα", "preparare, equipaggiare, fornire"),
("κατηγορέω, κατηγορήσω, κατηγόρησα, κατηγόρηκα, κατηγόρημαι, κατηγορήθην", "accusare, incolpare (+gen)"),
("κελεύω, κελεύσω, ἐκέλευσα, κεκέλευκα, κεκέλευσμαι, ἐκελεύσθην", "ordinare, invitare (+acc e infin.)"),
("κεῖμαι, κείσομαι", "giacere, trovarsi, essere stabilito (usato come perfetto passivo di τίθημι)"),
("κινέω, κινήσω, ἐκίνησα, κεκίνηκα, κεκίνημαι, ἐκινήθην", "muovere, mettere in moto; agitare"),
("κομίζω, κομιῶ, ἐκόμισα, κεκόμικα, κεκόμισμαι, ἐκομίσθην", "prendersi cura di, provvedere a"),
("κρατέω, κρατήσω, ἐκράτησα, κεκράτηκα, κεκράτημαι, ἐκρατήθην", "vincere, conquistare, prevalere, eccellere (+gen)"),
("κρίνω, κρινῶ, ἔκρινα, κέκρικα, κέκριμαι, ἐκρίθην", "giudicare, decidere, determinare"),
("κτάομαι, κτήσομαι, ἐκτησάμην, κέκτημαι", "acquistare, guadagnare; possedere"),
("κωλύω, κωλύσω, ἐκώλυσα, κεκώλυκα, κεκώλυμαι, ἐκωλύθην", "impedire (+acc e infinito)"),
("λαλέω, λαλήσω, ἐλάλησα, λελάληκα, ἐλαλήθην", "parlare, chiacchierare, raccontare"),
("λαμβάνω, λήψομαι, ἔλαβον, εἴληφα, εἴλημμαι, ἐλήφθην", "prendere"),
("λανθάνω, λήσω, ἔλαθον, λέληθα", "nascondersi; sfuggire all'attenzione di (+acc e nominativo del participio), essere ignoto; (al medio e passivo) dimenticare, dimenticarsi"),
("λέγω, ἐρῶ, εἶπον, εἴρηκα, λέλεγμαι, ἐλέχθην and ἐρρήθην", "dire; parlare"),
("λείπω, λείψω, ἔλιπον, λέλοιπα, λέλειμμαι, ἐλείφθην", "lasciare, abbandonare"),
("λύω, λύσω, ἔλυσα, λέλυκα, λέλυμαι, ἐλύθην", "sciogliere, liberare; distruggere"),
("μανθάνω, μαθήσομαι, ἔμαθον, μεμάθηκα", "imparare"),
("μάχομαι, μαχοῦμαι, ἐμαχεσάμην, μεμάχημαι", "combattere contro (+dat)"),
("μέλλω, μελλήσω, ἐμέλλησα", "(+infinito) essere in procinto di, pensare di fare"),
("μένω, μενῶ, ἔμεινα, μεμένηκα", "stare, rimanere; resistere; aspettare"),
("μίγνυμι, μείξω, ἔμειξα, μέμειγμαι, ἐμείχθην", "mescolare"),
("μιμνήσκω, -μνήσω, -έμνησα, pf. μέμνημαι, ἐμνήσθην", "rammentare; (al perfetto medio) ricordarsi"),
("νικάω, νικήσω, ἐνίκησα, νενίκηκα, νενίκημαι, ἐνικήθην", "vincere, conquistare"),
("νομίζω, νομιῶ, ἐνόμισα, νενόμικα, νενόμισμαι, ἐνομίσθην", "pensare, ritenere (+acc e infin.); essere abituati a (+infin.)"),
("οἶδα, infin. εἰδέναι, imper. ἴσθι, piucchepf. usato come impf. ᾔδειν", "sapere (perf. con forza di pres.); sapere come (+infin.)"),
("οἰκέω, οἰκήσω, ᾤκησα, ᾤκηκα, ᾠκήθην", "abitare, insediarsi"),
("οἴομαι/οἶμαι, οἰήσομαι, impf. ᾤμην, aor. ᾠήθην", "pensare (+acc e infin.)"),
("ὁμολογέω, ὁμολογήσω, ὡμολόγησα, ὡμολόγηκα, ὡμολόγημαι, ὡμολογήθην", "accordarsi, essere d'accordo (+dat)"),
("ὀνομάζω, ὀνομάσω, ὠνόμασα, ὠνόμακα, ὠνόμασμαι, ὠνομάσθην", "chiamare per nome"),
("ὁράω, ὄψομαι, 2 aor. εἶδον, ἑόρακα and ἑώρακα, ὤφθην, impf. ἑώρων", "vedere; guardare"),
("ὁρμάω, ὁρμήσω, ὥρμησα, ὥρμηκα, ὥρμημαι, ὡρμήθην", "mettere in moto, spingere; (intrans.) partire, affrettarsi"),
("πάρειμι", "essere presenti; (impers.) πάρεστί μοι dipende da me; τὰ παρόντα le circostanze presenti; τὸ παρόν solo ora"),
("παρέχω, παρέξω, παρέσχον, παρέσχηκα, impf. παρεῖχον", "procurare"),
("παραδίδωμι, παραδώσω, παρέδωκα, παραδέδωκα, παραδέδομαι, παρεδόθην", "trasmttere, consegnare; cedere"),
("παρασκευάζω, παρασκευάσω, παρεσκεύασα", "approntare, preparare"),
("πάσχω, πείσομαι, ἔπαθον, πέπονθα", "soffrire, provare; essere affetti in un certo modo (+avv)"),
("παύω, παύσω, ἔπαυσα, πέπαυκα, πέπαυμαι, ἐπαύθην", "far cessare; (la medio) smettere"),
("πείθω, πείσω, ἔπεισα, πέποιθα, πέπεισμαι, ἐπείσθην", "persuadere; (al medio e passivo) obbedire, credere in (+dat)"),
("πειράω (usually al medio πειράομαι), πειράσομαι, ἐπείρασα, πεπείραμαι, ἐπειράθην", "provare, tentare; fare prova di (+gen)"),
("πέμπω, πέμψω, ἔπεμψα, πέπομφα, πέπεμμαι, ἐπέμφθην", "mandare, inviare"),
("πίνω, πίομαι, 2 aor. ἔπιον, πέπωκα, -πέπομαι, -επόθην", "bere"),
("πίπτω, πεσοῦμαι, ἔπεσον, πέπτωκα", "cadere; soccombere"),
("πιστεύω, πιστεύσω, ἐπίστευσα, πεπίστευκα, πεπίστευμαι, ἐπιστεύθην", "fidarsi, credere, trust, affidarsi, credere in (+dat)"),
("πλέω, πλεύσομαι, ἔπλευσα, πέπλευκα, πέπλευσμαι, ἐπλεύσθην", "navigare"),
("ποιέω, ποιήσω, ἐποίησα, πεποίηκα, πεποίημαι, ἐποιήθην", "fare; creare; (al medio) considerare, riconoscere"),
("πολεμέω, πολεμήσω, ἐπολέμησα, πεπολέμηκα", "fare guerra; litigare"),
("πορεύω, πορεύσω, ἐπόρευσα, πεπόρευμαι, ἐπορεύθην", "portare; (al medio e passivo) recarsi, andare, viaggiare"),
("πράσσω, πράξω, ἔπραξα, πέπραχα, πέπραγμαι, ἐπράχθην", "fare, eseguire; fare in un certo modo (+avv)"),
("προσήκω προσήξω", "convenire; essere adatto (+dat); arrivare a; οἱ προσήκοντες i parenti; τὰ προσήκoντα i doveri"),
("προστίθημι, προσθήσω, προσέθηκα, προστέθηκα, προστέθειμαι (ma comunemente προσκεῖμαι), προσετέθην", "applicare; adoperare; (al medio) unirsi a"),
("πυνθάνομαι, πεύσομαι, 2 aor. ἐπυθόμην, πέπυσμαι", "informarsi; venire a sapere; chiedere a proposito di (+gen)"),
("σκοπέω, σκοπήσω, ἐσκόπησα", "osservare, guardare; considerare; esaminare"),
("συμβαίνω, συμβήσομαι, 2 aor. συνέβην, συμβέβηκα", "incontrare; accordarsi, correspond; accadere, succedere; avvenire in un certo modo (+avv), riuscire"),
("συμφέρω, συνοίσω, συνήνεγκα", "beneficiare, essere utile o vantaggioso a (+dat); (impers.) συμφέρει conviene, è vantaggioso (+infin.); τὸ συμφέρον l'utile, il vantaggio, il profitto"),
("σῴζω, σώσω, ἔσωσα, σέσωκα, ἐσώθην", "salvare"),
("τάσσω, τάξω, ἔταξα, τέταχα, τέταγμαι, ἐτάχθην", "disporre; schierare"),
("τελευτάω, τελευτήσω, ἐτελεύτησα, τετελεύτηκα, τετελεύτημαι, ἐτελευτήθην", "finire; morire"),
("τέμνω, τεμῶ, 2 aor. ἔτεμον, -τέτμηκα, τέτμημαι, ἐτμήθην", "tagliare, dividere, spaccare"),
("τίθημι, θήσω, ἔθηκα, τέθηκα, τέθειμαι (but usu. κεῖμαι instead), ἐτέθην", "porre, collocare; stabilire, ordinare, istituire; mettere in un certo stato"),
("τίκτω, τέξω or τέξομαι, ἔτεκον, τέτοκα, τέτεγμαι, ἐτέχθην", "generare, dare alla luce, produrre"),
("τιμάω, τιμήσω, ἐτίμησα, τετίμηκα, τετίμημαι, ἐτιμήθην", "onorare"),
("τολμάω, τολμήσω, ἐτόλμησα, τετόλμηκα, τετόλμημαι, ἐτολμήθην", "osare, avere coraggio; sopportare"),
("τρέπω, τρέψω, ἔτρεψα, τέτροφα, ἐτράπην", "volgere"),
("τρέφω, θρέψω, ἔθρεψα, τέθραμμαι, ἐτράφην", "nutrire"),
("τυγχάνω, τεύξομαι, ἔτυχον, τετύχηκα. τέτυγμαι, ἐτύχθην", "avere dalla sorte (+gen); ottenere, trovarsi (+partic.)"),
("ὑπάρχω, ὑπάρξω, ὑπῆρξα, ὑπῆργμαι, ὑπήρχθην", "esserci, esistere; τὰ ὑπάρχοντα le circostanze attuali"),
("ὑπολαμβάνω, ὑπολήψομαι, ὑπέλαβον, ὑπείληφα, ὑπείλημμαι, ὑπελήφθην", "prendere; rispondere; pensare"),
("φαίνω, φανῶ, ἔφηνα, πέφηνα, πέφασμαι, ἐφάνην", "mostrare; (al medio) apparire (+partic. or infin.)"),
("φέρω, οἴσω, 1 aor. ἤνεγκα, 2 aor. ἤνεγκον, ἐνήνοχα, ἐνήνεγμαι, ἠνέχθην", "portare; produrre; φέρε come now, well"),
("φεύγω, φεύξομαι, ἔφυγον, πέφευγα", "fuggire; essere imputato"),
("φημί, φήσω, impf. ἔφην", "affermare; οὐ φημί negare, dire che... no"),
("φοβέω, φοβήσω, ἐφόβησα, πεφόβημαι, ἐφοβήθην", "far paura; (al medio e passivo) temere, fuggire"),
("φράζω, φράσω, ἔφρασα, πέφρακα, πέφρασμαι, ἐφράσθην", "rivelare, annunciare; (al medio and pass.) riflettere"),
("φρονέω, φρονήσω, ἐφρόνησα", "pensare (+infin.); essere propenso a (+avv. e dat.)"),
("φυλάσσω, φυλάξω, ἐφύλαξα, πεφύλαχα, πεφύλαγμαι, ἐφυλάχθην", "fare la guardia, difendere; (al medio) guardarsi da (+acc)"),
("φύω, φύσω, ἔφυσα", "produrre, generare, mettere fuori; 2 aor. ἔφυν far crescere, pf. πέφυκα essere per natura"),
("χαίρω, χαιρήσω, κεχάρηκα, κεχάρημαι, ἐχάρην", "essere lieto, gioire a (+dat), godere a (+partic.); χαῖρε, (pl.) χαίρετε salve a tutti"),
("χράομαι, χρήσομαι, ἐχρησάμην, κέχρημαι, ἐχρήσθην", "usare (+dat); trattare qualcuno in un certo modo (+dat e avverbio)"),
("χρή, impf. χρῆν or ἐχρῆν, infin. χρῆναι", "essere necessario (+infin. o +acc e infin.)"),
]

DCC500_NOMI = [
("ἀγών, ἀγῶνος, ὁ", "contest; struggle"),
("ἀδελφός, –οῦ, ὁ", "gratello"),
("αἷμα, αἵματος, τό", "blood"),
("αἰτία, αἰτίας, ἡ", "causa; colpa; accusa"),
("ἀλήθεια, ἀληθείας, ἡ", "verità"),
("ἀνάγκη, ἀνάγκης, ἡ", "necessity"),
("ἄνθρωπος, –ου, ὁ/ἡ", "essere umano"),
("ἀνήρ, ἀνδρός, ὁ", "uomo, marito"),
("ἀργύριον, ἀργυρίου, τό", "money"),
("ἀρετή, ἀρετῆς, ἡ", "eccellenza; virtù; valore militare, coraggio"),
("ἀριθμός, –οῦ, ὁ", "numero"),
("ἀρχή, ἀρχῆς, ἡ", "inizio, origine; comando"),
("βασιλεύς, βασιλέως, ὁ", "re"),
("βίος, βίου, ὁ", "vita"),
("βουλή, βουλῆς, ἡ", "volontà, determinazione; consiglio"),
("βοῦς, βοός, ὁ/ἡ", "bull, ox, cow"),
("γένος, γένους, τό", "race, family; kind, class"),
("γῆ, γῆς, ἡ", "terra, territorio"),
("γνώμη, γνώμης, ἡ", "pensiero, sentenza, proverbio"),
("γλῶσσα, γλώσσης, ἡ", "tongue; language"),
("γράμμα, γράμματος, τό", "letter, written character; (pl.) piece of writing, document(s)"),
("γραφή, γραφῆς, ἡ", "a drawing, painting, writing; indictment"),
("γυνή, γυναικός, ἡ", "donna, moglie"),
("δίκη, δίκης, ἡ", "giustizia; processo"),
("δαίμων, δαίμονος, ὁ/ἡ", "spirit, god, demon"),
("δεσπότης, –ου, ὁ", "master (of the household); absolute ruler"),
("διαφορά, –ᾶς, ἡ", "difference, disagreement"),
("δοῦλος, δούλου, ὁ", "slave"),
("δόξα, δόξης, ἡ", "opinion, judgment; reputation, honor, glory"),
("δύναμις, δυνάμεως, ἡ", "potenza; esercito"),
("δῆμος, δήμου, ὁ", "popolo; distretto (opp. πόλις)"),
("ἔθνος, ἔθνους, τό", "nation"),
("ἐλπίς, ἐλπίδος, ἡ", "hope; expectation"),
("εἶδος, εἴδους, τό", "form, shape, figure; class, kind, sort"),
("εἰκός, εἰκότος, τό", "likelihood, probability; εἰκός (ἐστι) it is likely (+infin.) →ἔοικα"),
("εἰρήνη, εἰρήνης, ἡ", "pace"),
("ἐπιστήμη –ης, ἡ", "knowledge, understanding, skill"),
("ἔπος, ἔπους, τό", "word, speech, tale; prophecy"),
("ἔργον, ἔργου, τό", "opera, impresa, lavoro"),
("ἔτος, ἔτους, τό", "anno"),
("ἡγεμών, ἡγεμόνος, ὁ", "guide, leader, commander"),
("ἡδονή, –ῆς, ἡ", "pleasure, enjoyment"),
("ἥλιος, ἡλίου, ὁ", "sole"),
("ἡμέρα, ἡμέρας, ἡ", "giorno"),
("ζῷον, ζῴου, τό", "living being, animal"),
("θάλασσα, θαλάσσης, ἡ", "il mare"),
("θάνατος, θανάτου, ὁ", "morte"),
("θεός,θεοῦ, ὁ/ἡ", "dio, dea"),
("θυγάτηρ, θυγατρός, ἡ", "figlia"),
("θυμός, θυμοῦ, ὁ", "life, spirit; soul, heart, mind"),
("ἱππεύς, ἱππέως, ὁ", "cavaliere"),
("ἵππος, ἵππου, ὁ", "cavallo"),
("καιρός, καιροῦ, ὁ", "the right Tempo"),
("κεφαλή, –ῆς, ἡ", "testa"),
("κίνδυνος, κινδύνου, ὁ", "pericolo, rischio"),
("κόσμος, κόσμου, ὁ", "order; ornament, decoration, adornment; world, universe"),
("κύκλος, κύκλου, ὁ", "circle, ring, orb, disc, circular motion"),
("κύριος, κυρίου, ὁ", "lord, master"),
("λαός, λαοῦ, ὁ", "the people, folk"),
("λίθος, λίθου, ὁ", "pietra"),
("λόγος, λόγου, ὁ", "parola; discorso; ragionamento"),
("μάρτυς, μάρτυρος, ὁ/ἡ", "witness"),
("μάχη, μάχης, ἡ", "battle"),
("μέγεθος, μεγέθους, τό", "greatness, size, magnitude"),
("μέρος, μέρους, τό", "part, share"),
("μήτηρ, μητρός, ἡ", "madre"),
("ναός (νεώς), ναοῦ (νεώ), ὁ", "tempio"),
("ναῦς, νεώς, ἡ", "nave"),
("νίκη, νίκης, ἡ", "vittoria"),
("νόμος, νόμου, ὁ", "legge; costume, tradizione"),
("νόσος, νόσου, ὁ", "disease, sickness"),
("νοῦς (νόος), νοῦ (νόου), ὁ", "mind, perception, sense"),
("νῆσος, νήσου, ἡ", "isola"),
("νύξ, νυκτός, ἡ", "notte"),
("ξένος, ξένου, ὁ", "guest-friend; foreigner, stranger"),
("ὁδός, ὁδοῦ, ἡ", "via, strada"),
("οἰκία, οἰκίας, ἡ", "casa"),
("οἶκος, οἴκου, ὁ", "casa; famiglia"),
("ὄνομα, ὀνόματος, τό", "nome; fama"),
("ὄρος, ὄρους, τό", "mountain, hill"),
("ὅπλον, ὅπλου, τό", "weapon, tool, implement (mostly pl.)"),
("ὀφθαλμός, –οῦ, ὁ", "occhio"),
("οὐρανός, –οῦ, ὁ", "cielo"),
("οὐσία, οὐσίας, ἡ", "substance, property; essence"),
("πάθος, πάθους, τό", "incident, accident, misfortune, experience; passion, emotion; state, condition"),
("πατήρ, πατρός, ὁ", "padre"),
("πατρίς, πατρίδος, ἡ", "fatherland"),
("παῖς, παιδός, ὁ/ἡ", "fanciullo, figlio, figlia; schiavo"),
("πίστις, πίστεως, ἡ", "trust in others, faith; that which gives confidence, assurance, pledge, guarantee"),
("πλῆθος, πλήθους, τό", "quantità, moltitudine, folla"),
("πνεῦμα, πνεύματος, τό", "wind, breath, spirit"),
("ποιητής, –οῦ, ὁ", "creatore, poeta"),
("πολιτεία, –ας, ἡ", "costituzione; governo; città"),
("ποταμός, –οῦ, ὁ", "fiume"),
("πούς, ποδός, ὁ", "piede"),
("πρᾶγμα, πράγματος, τό", "fatto, azione, impresa, cosa"),
("πρᾶξις, πράξεως, ἡ", "action, transaction, business"),
("πρέσβυς, πρέσβεως, ὁ", "old man; (pl.) ambassadors"),
("πόλεμος, πολέμου, ὁ", "guerra"),
("πόλις, πόλεως, ἡ", "città, città-stato"),
("πόνος, πόνου, ὁ", "work, labor; stress, trouble, pain"),
("πρόσωπον, προσώπου, τό", "face, mask, person"),
("πῦρ, πυρός, τό", "fuoco"),
("σημεῖον, σημείου, τό", "sign, signal, mark"),
("στάδιον, σταδίου, τό (pl. στάδια and στάδιοι)", "stadion or stade, the longest Greek unit of linear measure, about 185 meters"),
("στρατηγός, –οῦ, ὁ", "leader of an army, commander, general"),
("στρατιά, –ᾶς, ἡ", "army"),
("στρατιώτης, –ου, ὁ", "soldier"),
("στρατός, –οῦ, ὁ", "army"),
("στόμα, στόματος, τό", "mouth, face, opening"),
("συμφορά, –ᾶς, ἡ", "event, circumstance, misfortune"),
("σχῆμα, σχήματος, τό", "form, figure, appearance, character"),
("σωτηρία, σωτηρίας, ἡ", "safety, deliverance"),
("σῶμα, σώματος, τό", "corpo, cadavere"),
("τάξις,τάξεως, ἡ", "arrangement, order; military unit"),
("τέκνον, τέκνου, τό", "figlio"),
("τέλος, τέλους, τό", "end, fulfillment, achievement"),
("τέχνη, τέχνης, ἡ", "art, skill, craft"),
("τεῖχος, τείχους, τό", "muro"),
("τιμή, τιμῆς, ἡ", "honor, esteem; price, value; office, magistracy"),
("τροφή, τροφῆς, ἡ", "nourishment, food"),
("τρόπος, τρόπου, ὁ", "way, manner, fashion; way of life, habit, custom"),
("τόπος, τόπου, ὁ", "luogo"),
("τύχη, τύχης, ἡ", "luck, fortune (good or bad), fate, chance"),
("ὕδωρ, ὕδατος, τό", "water"),
("υἱός, υἱοῦ, ὁ", "figlio"),
("φωνή, φωνῆς, ἡ", "voce; suono"),
("φόβος, φόβου, ὁ", "paura; fuga"),
("φύσις, φύσεως, ἡ", "natura"),
("φῶς, φωτός, τό", "light, daylight"),
("χάρις, χάριτος, ἡ", "splendor, honor, glory; favor, goodwill, gratitude, thanks"),
("χείρ, χειρός, ἡ", "mano"),
("χρόνος, χρόνου, ὁ", "tempo"),
("χρῆμα, χρήματος, τό", "thing, matter; (more commonly in pl.) goods or property, esp. money"),
("χωρίον, χωρίου, τό", "place, spot, district"),
("χώρα, χώρας, ἡ", "regione; territorio"),
("ψυχή, ψυχῆς, ἡ", "anima, soffio vitale"),
]

DCC500_AGGETTIVI = [
("αἰσχρός, –ά, –όν", "turpe, brutto"),
("αἴτιος, αἰτία, αἴτιον", "colpevole, responsabile"),
("ἀγαθός, –ή, –όν", "buono, virtuoso, coraggioso, nobile"),
("ἀδύνατος, –ον", "impotente; impossibile"),
("ἀκριβής, –ές", "exact, accurate, precise"),
("ἀληθής, –ές", "vero"),
("ἀλλήλων, –οις", "(oblique cases plural only) one another, each other"),
("ἀμείνων, ἄμεινον", "better, abler, stronger, braver (comparativo di ἀγαθός)"),
("ἀμφότερος, ἀμφοτέρα, ἀμφότερον", "both"),
("ἄδικος, ἄδικον", "ingiusto"),
("ἄλλος, ἄλλη, ἄλλο", "altro"),
("ἄξιος, ἀξία, ἄξιον", "worthy, deserving"),
("ἅπας, ἅπασα, ἅπαν", "all together"),
("ἄριστος, ἀρίστη, ἄριστον", "best, noblest (superlativo di ἀγαθός)"),
("αὐτός, αὐτή, αὐτό", "him- her- itself etc. (for emphasis); the same (with article); (pron.) him, her, it etc. (in oblique cases)"),
("βάρβαρος, –ον", "barbaro; non Greco, straniero"),
("βαρύς, βαρεῖα, βαρύ", "heavy, grievous, tiresome"),
("βελτίων, βέλτιον", "better (comparativo di ἀγαθός)"),
("βραχύς, βραχεῖα, βραχύ", "corto, breve"),
("δέκα", "dieci"),
("δέκατος, –η, –ον", "decimo"),
("δίκαιος, δικαία, δίκαιον", "giusto"),
("δεινός, –ή, –όν", "terribile; esperto, esperto in/a (+infin.)"),
("δεύτερος, –α, –ον", "secondo"),
("δυνατός, –ή, –όν", "strong, powerful, able"),
("δύο", "due"),
("δῆλος, δήλη, δῆλον", "visible, clear, manifest"),
("εἰκοστός, –ή –όν", "ventesimo"),
("εἴκοσι(ν)", "venti"),
("εἷς, μία, ἕν", "uno"),
("εὐθύς εὐθεῖα εὐθύ", "straight, direct; (adv.) immediately"),
("ἐγώ, ἐμοῦ, (plur.) ἡμεῖς, ἡμῶν", "io, noi"),
("ἐκεῖνος, ἐκείνη, ἐκεῖνον", "quello, quella, quella cosa; ἐκεῖνος... οὗτος quello... questo"),
("ἐλάσσων, ἔλασσον", "smaller, less, fewer (comparativo di μικρός)"),
("ἐλεύθερος, ἐλευθέρα, ἐλεύθερον", "libero"),
("ἐμός, ἐμή, ἐμόν", "mio"),
("ἐννέα", "nove"),
("ἐχθρός, –ά, –όν", "avverso, nemico; ostile a (+dat)"),
("ἑαυτοῦ, ἑαυτῆς, ἑαυτοῦ", "him- her- itself (reflexive pron.)"),
("ἑκάτερος, ἑκατέρα, ἑκάτερον", "each (of two)"),
("ἑκατοστός, –ή, –όν", "centesimo"),
("ἑκατόν", "cento"),
("ἑπτά", "sette"),
("ἔνατος, –α, –ον", "nono"),
("ἕβδομος, –η, –ον", "settimo"),
("ἕκαστος, ἑκάστη, ἕκαστον", "ciascuno"),
("ἕκτος, –η, –ον", "sesto"),
("ἕξ", "sei"),
("ἕτερος, ἑτέρα, ἕτερον", "altro (di due); solitario; privo, mancante"),
("ἡδύς, ἡδεῖα, ἡδύ", "dolve, soave"),
("ἡμέτερος, ἡμετέρα, ἡμέτρον", "our"),
("ἥσσων, ἧσσον", "less, weaker (comparativo di κακός o μικρός)"),
("θεῖος, θεία, θεῖον", "divino"),
("ἰσχυρός, –ά, –όν", "forte"),
("ἱερός, –ά, –όν", "sacro"),
("ἱκανός, –ή, –όν", "sufficente; competente, abile a (+infin.)"),
("ἴδιος, ἰδία, ἴδιον", "proprio, peculiare"),
("ἴσος, ἴση, ἴσον", "equal, the same as (+dat)"),

("κακός, –ή, –όν", "cattivo, vile"),
("καλός, –ή, –όν", "bello"),
("κοινός, –ή, –όν", "comune"),
("κρείσσων, κρεῖσσον", "stronger, mightier; better, more excellent (comp. of ἀγαθός)"),
("λαμπρός, –ά, –όν", "bright, brilliant; well-known, illustrious"),
("λοιπός, –ή, –όν", "rimanente"),
("μέγας, μεγάλη, μέγα", "grande, grande cosa"),
("μέσος, μέση, μέσον", "mezzo, mediano; τὸ μέσον il mezzo"),
("μακρός, –ά, –όν", "long, tall, large, long-lasting"),
("μηδείς, μηδεμία, μηδέν", "no one, nothing"),
("μικρός, –ά, –όν", "piccolo"),
("μυρίος, μυρία, μυρίον", "countless; μύριοι 10,000; μυριάς -άδος ἡ 10,000, a countless amount"),
("μόνος, μόνη, μόνον", "solo"),
("νέος, νέα, νέον", "nuovo; giovane"),
("οἰκεῖος, οἰκεία, οἰκεῖον", "domestic, of the house; one’s own; fitting, suitable"),
("οἷος, οἵα, οἷον", "such as, of what sort, like, (exclam.) what a!, how! ; οἷός τε (+infin.) fit or able to; οἷόν τε (+infin.) it is possible to"),
("οὐδείς, οὐδεμία, οὐδέν", "nessuno, nulla"),
("οὗτος, αὕτη, τοῦτο", "questo, questi; μετὰ ταῦτα dopo questo"),
("ὀκτώ", "otto"),
("ὀλίγος, ὀλίγη, ὀλίγον", "piccolo, poco"),
("ὀξύς, ὀξεῖα, ὀξύ", "sharp, keen, shrill, pungent"),
("ὀρθός, –ή, –όν", "upright, straight, true, regular"),
("ὄγδοος, –η, –ον", "ottavo"),
("ὅδε, ἥδε, τόδε", "questo, questa"),
("ὅλος, ὅλη, ὅλον", "tutto quanto, intero"),
("ὅμοιος, ὁμοία, ὅμοιον", "simile, uguale (+dat)"),
("ὅς, ἥ, ὅ", "chi, il quale"),
("ὅσος, ὅση, ὅσον", "quanto; (al pl.) tanti quanti; ὅσον (avv.) tanto quanto"),
("ὅσπερ, ἥπερ, ὅπερ", "the very one who, the very thing which"),
("ὅστις, ἥτις, ὅ τι", "anyone who, anything which; (in indir. quest.) who, which, what"),
("πέντε", "cinque"),
("παλαιός, –ά, –όν", "old, ancient"),
("πεμπτός, –ή, –όν", "quinto"),
("πλέων, πλέον", "more, larger (comp. of πολύς)"),
("πλεῖστος, πλείστη, πλεῖστον", "most, greatest, largest (superl. of πολύς)"),
("πολέμιος, πολεμία, πολέμιον", "nemico; οἱ πολέμιοι il nemico"),
("πολύς, πολλή, πολύ", "molto, tanto; ὡς ἐπὶ τὸ πολύ per la maggior parte"),
("πονηρός, –ά, –όν", "malvagio"),
("ποῖος, ποία, ποῖον", "what sort of?"),
("ποῦ", "dove"),
("πρότερος, προτέρα, πρότερον", "before, earlier; τὸ πρότερον previously, before"),
("πρῶτος, πρώτη, πρῶτον", "primo; (avv.) τὸ πρῶτον al primo posto"),
("πότερος, ποτέρα, πότερον", "which of the two? πότερον whether"),
("πᾶς, πᾶσα, πᾶν", "tutto; ogni"),
("ῥᾴδιος, ῥᾳδία, ῥᾴδιον", "facile"),
("σαφής, σαφές", "clear, distinct, plain"),
("σοφός, –ή, –όν", "sapiente"),
("σός, σή, σόν", "tuo, tuoi (sing.; ὑμέτερος = plur.)"),
("σύ, σοῦ, (plur.) ὑμεῖς, ὑμῶν", "tu, voi"),
("σύμμαχος, –ον", "alleato con (+dat); οἱ σύμμαχοι gli alleati"),
("τέταρτος, –η, –ον", "quarto"),
("τέτταρες, τέτταρα", "quattro"),
("τίς, τί", "chi? cosa? quale? (pron./agg. interrogativo)"),
("ταχύς, ταχεῖα, ταχύ", "veloce; (avv.) τάχα velocemente; forse"),
("τις, τι", "someone, something, anyone, anything, some, any (pron./agg. indefinito enclitico)"),
("τοιοῦτος, τοιαύτη, τοιοῦτο", "tale, siffatto"),
("τοιόσδε, τοιάδε, τοιόνδε", "such (as this), of such a sort (as this)"),
("τοσοῦτος, τοσαύτη, τοσοῦτο(ν)", "così grande"),
("τρίτος, –η, –ον", "terzo"),
("τρεῖς, τρία", "tre"),
("τριάκοντα", "trenta"),
("τριακοστός, –ή, –όν", "trentesimo"),
("ὑμέτερος, ὑμετέρα, ὑμέτερον", "vostro, vostri (plur.; σός = sing.)"),
("ὕστερος, ὑστέρα, ὕστερον", "coming after, following (+gen); next, later; (adv.) ὕστερον afterwards"),
("φίλος, φίλη, φίλον", "amico; caro"),
("φανερός, –ά, –όν", "evidente, manifesto; famoso"),
("χαλεπός, –ή, –όν", "difficile; intrattabile"),
("χαλκοῦς, –ῆ, –οῦν", "bronzeo, di bronzo"),
("χείρων, χεῖρον", "worse, inferior (comparativo. di κακός)"),
("χρήσιμος, χρησίμη, χρήσιμον", "utile"),
]

DCC500_MISC = [
("ἀεί", "sempre", "avverbio"),
("ἀλλά", "ma", "congiunzione: coordinativa"),
("ἀμφί", "a causa (+gen); intorno, presso (+dat, +acc); ", "preposizione"),
("ἀνά", "sopra, su (+gen, +dat, +acc); per, attraverso (+gen, +dat, +acc)", "preposizione"),
("ἀντί", "di fronte, contro (+gen)", "preposizione"),
("ἄλλως", "altrimenti", "avverbio"),
("ἁπλῶς", "simply, singly, in one way", "avverbio"),
("ἀπό", "da (+gen)", "preposizione"),
("ἅμα", "insieme; mentre; (prep.) insieme con (+dat)", "avverbio"),
("ἄν", "[segna il verbo come potenziale (con ottativo), o eventuale (con congiuntivo)]", "avverbio"),
("ἄνευ", "senza (+gen)", "preposizione"),
("ἄνω", "su, in alto", "avverbio"),
("ἄρα", "allora, quindi [introduce un'inferenza]", "avverbio"),
("ἆρα", "e non?, forse? [introduce una domanda]", "avverbio"),
("αὐτίκα", "subito, immediatamente", "avverbio"),
("αὖ, αὖθις", "inoltre; d'altra parte; un'altra volta (ancora)", "avverbio"),
("γάρ", "perché (esplicativo), davvero, infatti (confermativo)", "congiunzione: coordinativa"),
("γε", "(enclitica) appunto, invero; almeno", "avverbio"),
("δέ", "e; ma", "congiunzione: coordinativa"),
("δή", "certamente, certo, infatti, davvero (enfatico, da maggiore esattezza)", "avverbio"),
("διά", "attraverso (+gen); per mezzo di (+acc)", "preposizione"),
("ἐάν (εἰ-ἄν)", "se (+cong)", "congiunzione: subordinativa"),
("εἰ", "se (+indic, +ott); εἴπερ se davvero", "congiunzione: subordinativa"),
("εἰς", "in, verso (+acc)", "preposizione"),
("εἶτα", "poi, in seguito; quindi", "avverbio"),
("εἴτε…εἴτε", "sia che... sia che", "congiunzione: coordinativa"),
("ἐκ, ἐξ", "da, fuori (+gen)", "preposizione"),
("ἐκεῖ", "là", "avverbio"),
("ἐν", "in, dentro, tra (+dat)", "preposizione"),
("ἐναντίος ἐναντία ἐναντίον", "di fronte, contro (+gen)", "preposizione"),
("ἕνεκα", "a causa di, al fine di (+gen)", "preposizione"),
("ἔνθα", "lì, là", "avverbio"),
("ἐνταῦθα", "qui; lì (+gen)", "avverbio"),
("ἔξω", "fuori, eccetto (+gen)", "avverbio e preposizione"),
("ἐπεί", "dopo; quando", "congiunzione: subordinativa"),
("ἔπειτα", "poi, in seguito", "avverbio"),
("ἐπί", "sopra, a, presso (+gen); sopra, su (+dat); sopra, verso (+acc)", "preposizione"),
("ἔτι", "ancora, inoltre", "avverbio"),
("εὖ", "bene (opp. κακῶς); giustamente, felicemente, fortunatamente", "avverbio"),
("ἕως", "finché; mentre", "congiunzione: subordinativa"),
("ἤ", "o, oppure; che (dopo un comparativo); ἤ...ἤ o...o", "congiunzione: coordinativa"),
("ἦ", "certo, senza dubbio (enfatizza quello che segue)", "avverbio"),
("ἤδη", "già (tempo passato); ora, già (tempo presente); ormai, subito (tempo futuro)", "avverbio"),
("ἵνα", "affinché, per (+cong, +ott); dove (avverbio di luogo +indic)", "congiunzione: subordinativa"),
("ἴσως", "ugualmente, allo stesso modo; forse, probabilmente", "avverbio"),
("καί", "e, anche, pure; καί...καί e...e, non solo...ma anche...", "congiunzione: coordinativa"),
("καίτοι (καί-τοι)", "certo, a dire il vero", "avverbio"),
("κἄν (καὶ-ἄν)", "anche se (+cong)", "congiunzione: subordinativa"),
("κατά", "giù, giù da (+gen), per (+gen, tempo) su, sopra, durante (+acc); κατὰ γῆν via terra; κατὰ φύσιν secondo natura; κατ’ ἔθνη attraverso i territori; καθ᾿ἕνα uno alla volta", "preposizione"),
("μάλα", "molto, assai", "avverbio"),
("μάλιστα", "most, most of all; (in replies) certainly", "avverbio"),
("μᾶλλον", "di più, piuttosto; μᾶλλον...ἤ piuttosto che", "avverbio"),
("μέν...δέ", "da una parte...dall'altra; μέν (da solo) davvero", "congiunzione: coordinativa"),
("μέντοι", "however; of course", "avverbio"),
("μέχρι (+gen)", "finché; fino a (prep. +gen)", "congiunzione: subordinativa"),
("μή", "non (negativo per il congiuntivo e il periodo ipotetico); εἰ μή se non, eccetto", "congiunzione: subordinativa"),
("μήν", "certo [enfatizza la particella precedente]", "avverbio"),
("μήτε...μήτε", "né...né", "congiunzione: coordinativa"),
("μετά", "con (+gen); in mezzo, dopo (+acc)", "preposizione"),
("μεταξύ", "in mezzo", "avverbio"),
("μηδέ", "e non", "congiunzione: coordinativa"),
("μόνον", "solo", "avverbio"),
("ναί", "davvero, si (usato in affermazioni forti)", "avverbio"),
("νῦν, νυνί", "ora", "avverbio"),
("ὁ, ἡ, τό", "il (articolo)", "articolo determinativo"),
("ὅθεν", "da dove, donde", "avverbio"),
("ὅμως", "tuttavia, peraltro; sebbene", "avverbio"),
("ὅπου", "dove; quando; poiché", "congiunzione: subordinativa"),
("ὅπως", "quando; affinché (+cong, +ott)", "congiunzione: subordinativa"),
("ὅταν (ὅτε-ἄν)", "quando, allorché (+cong)", "congiunzione: subordinativa"),
("ὅτε", "quando, allorché (+indic, +ott)", "congiunzione: subordinativa"),
("ὅτι", "perché, che; (col superlativo) al più presto, il più possibile", "congiunzione: subordinativa"),
("οὐ, οὐκ, οὐχ", "non (con verbi all'indicativo)", "avverbio"),
("οὐδέ", "e non, ma non, nemmeno, neppure; οὐδέ...οὐδέ né...né", "congiunzione: coordinativa"),
("οὐκέτι", "no longer, no more", "avverbio"),
("οὐκοῦν", "sicché, perciò (invita a dire di sì a un'affermazione)", "avverbio"),
("οὖν", "dunque, senza dubbio, infatti", "avverbio"),
("οὔτε...οὔτε", "né...né", "congiunzione: coordinativa"),
("οὕτως", "in questo modo, così", "avverbio"),
("πάλιν", "di nuovo; indietro, al contrario", "avverbio"),
("πάντως", "del tutto, assolutamente, in ogni caso", "avverbio"),
("πάνυ", "del tutto, affatto, totalmente", "avverbio"),
("παρά", "da (+gen); presso, accanto (+dat); a, verso, al contrario (+acc)", "preposizione"),
("περ", "assai, proprio; sebbene [enclitica aggiunta a pronomi e altre particelle per enfasi]", "avverbio"),
("περί", "intorno, riguardo a (+gen); presso, per (+dat); lungo, verso (+acc)", "preposizione"),
("πλέον", "più, piuttosto", "avverbio"),
("πλήν", "(prep.) eccetto, tranne (+gen); (congiunzione) exxetto che, a meno che, ma", "preposizione"),
("πολλάκις", "spesso", "avverbio"),
("ποτε", "(enclitica) quando, i quel tempo, una volta", "avverbio"),
("πότε", "quando?", "avverbio"),
("που", "(enclitica) in qualche luogo; in qualche modo, forse (per precisare un'affermazione)", "avverbio"),
("πρίν", "prima; finché non", "congiunzione: subordinativa"),
("πρό", "prima, davanti (+gen)", "preposizione"),
("πρός", "dalla parte di, innanzi (+gen); presso, su, a in (+dat); a, verso (+acc)", "preposizione"),
("πως", "(enclitica) in qualche modo, come che sia", "avverbio"),
("πῶς", "come?", "avverbio"),
("σύν", "con (+ dat. di compagnia o mezzo)", "preposizione"),
("τε", "e; τε...τε sia...sia", "congiunzione: coordinativa"),
("τοίνυν (τοί-νυν)", "quindi, in accordo con (inferenzale); inoltre, in più (transizionale)", "avverbio"),
("τότε", "allora, in quel tempo; οἱ τότε gli uomini di quel tempo (opposto a οἱ νῦν)", "avverbio"),
("ὑπέρ", "al di là, per (+gen), oltre (+acc)", "preposizione"),
("ὑπό", "sotto (+gen, +dat); da (+gen di agente personale); sotto (+acc moto a luogo)", "preposizione"),
("χωρίς", "separatamente, a parte; (+gen) senza, differentemente", "avverbio"),
("ὦ", "oh! (quando è con il vocativo non è enfatico)", "interiezione"),
("ὧδε", "così, in questo modo; a tal punto; qui", "avverbio"),
("ὡς", "come, nel modo che; affinché (+cong/+ott, introduce una subordinata finale); che (introduce un discorso indiretto)", "congiunzione: subordinativa"),
("ὥσπερ", "come se, finché", "congiunzione: subordinativa"),
("ὥστε", "cosicché, in modo che (introduce una subordinata consecutiva), (con il risultato) che", "congiunzione: subordinativa"),
]